### ISSUE TITLE
Feature request: rundeck restart logic

### ISSUE THREAD

**Issue by reigner-yrastorza** [rundeck/rundeck#1108] opened 2015-02-13 23:30 UTC
When rundeck is restarted through the init script, it will stop all the jobs that is currently running.

Can it have a logic, where it checks if there are jobs currently running before it restarts?

It should also prohibits next job to be run. 

This is somehow similar to what jenkins have, when you restart it.

OS: CentOS 6.5
Rundeck version: 2.4.1

Thanks,
Reigner S. Yrastorza

**Comment by xiaods** [comment] 2015-02-14 03:33
I suggest format the request:
1. checks if there are jobs currently running before it restarts
2. parsed the running jobs first, then restarts.
3. It should also prohibits next job to be run.

**Comment by starplanet** [comment] 2017-08-23 06:09
+1. this feature has not been added until now.

**Comment by gschueler** [comment] 2017-08-25 16:32
duplicate of #1033

**Closed by gschueler** 2017-08-25 16:32 UTC
Labels: enhancement
