### ISSUE TITLE
UI Error: "Project does not exist" when working on another project

### ISSUE THREAD

**Issue by DoomStar** [rundeck/rundeck#4502] opened 2019-02-14 14:12 UTC
**Describe the bug**

Trying to add a job to a project named "LNX", the UI throws an error "Project does not exist" referring to another project "Anvils" that has been deleted.

```
Error 500: Internal Server Error

URI
    /rundeck/project/LNX/job/create
Class
    com.dtolabs.rundeck.core.common.NoSuchResourceException
Message
    Project does not exist: Anvils
```

**My Rundeck detail**

    * Rundeck version: 3.0.2

    * install type: deb

    * OS Name/version: Ubuntu 16.04

    * DB Type/version: h2

    * Rundeck runs behind nginx (location: /rundeck/).

**To Reproduce**

    1. Create a project "LNX"

    2. Create a project "Anvils"

    3. Delete "Anvils"

    4. Try to create a job in "LNX"

Restarting Rundeck, the error disappears.

**Other information**

Part of the Java Exception

```
com.dtolabs.rundeck.core.common.NoSuchResourceException: Project does not exist: Anvils
        at com.dtolabs.rundeck.core.common.FrameworkProjectMgr.getFrameworkProject(FrameworkProjectMgr.java:202)
        at com.dtolabs.rundeck.core.common.FrameworkProjectMgr.getFrameworkProject(FrameworkProjectMgr.java:28)
        at com.dtolabs.rundeck.core.common.FrameworkBase.getProjectProperty(FrameworkBase.java:251)
        at com.dtolabs.rundeck.core.common.PluginControlServiceImpl.listDisabledPlugins(PluginControlServiceImpl.java:33)
        at com.dtolabs.rundeck.core.common.PluginControlServiceImpl.isDisabledPlugin(PluginControlServiceImpl.java:87)
        at rundeck.controllers.ScheduledExecutionController$_create_closure75.doCall(ScheduledExecutionController.groovy:2364)
        at rundeck.controllers.ScheduledExecutionController.create(ScheduledExecutionController.groovy:2363)
        at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
```

**Comment by DoomStar** [comment] 2019-02-14 14:13
https://github.com/rundeck/rundeck/issues/3905 (bug closed but still exists)

**Comment by reinerrdeck** [comment] 2019-02-23 01:24
Issue confirmed on 3.0.14.

**Comment by gschueler** [comment] 2019-04-22 19:00
duplicate of #3905

**Closed by gschueler** 2019-04-22 19:00 UTC
Labels: bug, status:reproduced
