### ISSUE TITLE
stdout and stderr logging is appearing out of order

### ISSUE THREAD

**Issue by spaced0gg** [rundeck/rundeck#6660] opened 2020-12-07 11:02 UTC
**Describe the bug**

We are running a Job with 2 steps:

* Script that outputs the version of a software package we are deploying
* Export global variable for software version

If there is no file to get the version from, we explicitly write "no_version" to stdout, which is then exported in the next step to a global variable.

This works 99.9% of the time. e.g.

00:31:01	versionFileName.txt - no such file(s).
00:31:01	RUNDECK:DATA:version=no_version

When the issue occurs, the stderr line indicating that there is no file and the stdout writing "no_version" appear on the same line in the execution log with a subsequent blank line :

00:31:01	versionFileName.txt - no such file(s).RUNDECK:DATA:version=no_version
00:31:01	

The regex we use to populate the global variable in step 2 is:

 Pattern: ^RUNDECK:DATA:(.+?)\s*=\s*(.+)$ 

This causes our step to fail as it is expecting the RUNDECK:DATA: to be at the start of the line.

**My Rundeck detail**

* Rundeck version: 3.2.8-20200608
* install type: rpm
* OS Name/version: RHEL 6.10 x86_64
* DB Type/version: mysql 5.1.73-8

**To Reproduce**
This issue happens sporadically,  I have not been able to consistently reproduce.

**Expected behavior**
Execution log output should appear in the order it is produced.

**Comment by spaced0gg** [comment] 2020-12-07 11:05
It looks like this issue could be related to these 2 issues:

* #1687 - stdout & stderr appearing out of order in script job output
* #1425 - Log output out of order

Both of these issues were closed without any indication that they have been fixed.

**Comment by ProTip** [comment] 2020-12-14 17:16
@spaced0gg Those issues appear to be for a separate issue; stdout and stderr being interleaved in non-chronological order(due to buffering).

In this issue it appears the entries are appearing on the same line which should never happen. I believe this was addressed in #6273. Please re-open if you are able to reproduce on the latest version of Rundeck(`3.3.7`).

**Closed by ProTip** 2020-12-14 17:16 UTC
