### ISSUE TITLE
Can not add NODE on version 3.x

### ISSUE THREAD

**Issue by modanisa** [rundeck/rundeck#4296] opened 2018-12-10 05:59 UTC
**Describe the bug**
Add node future not working on 3.x versions.
resources.xml file not coming as default installation.

**My Rundeck detail**

* Rundeck version: 3.x
* install type: rpm
* OS Name/version: AWS Linux 2
* DB Type/version: default (no db)

**To Reproduce**
1. Go to 'NODES'
2. Click on 'SHOW ALL NODES'
4. No show added nodes in config. Also no coming this file "resources.xml" when installation completed.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Additional context**

**Comment by SqlAdmin** [comment] 2018-12-23 22:42
I was using Rundeck 3.0.6-20180917 on Centos7. Im also facing the same issue even after added these lines.

I fixed it by just setting the file manually.

touch resouces.xml

vi resources.xml

```<?xml version="1.0" encoding="UTF-8"?>
<project>
<node name="replica02"  tags="mysql" hostname="10.0.0.1" osArch="amd64" osFamily="unix" osName="Linux" osVersion="4.9.0-2-amd64" username="rundeck"/>
</project>```

Then set the permission.
`chown rundeck:rundeck resources.xml`

**Comment by SqlAdmin** [comment] 2019-01-20 12:32
In newer versions, it has different ways to add nodes. So people still use the same oldest method, requesting you to check the new ways.

[You can read this to understand different ways of adding nodes. ](https://www.sqlgossip.com/add-nodes-to-the-rundeck/)

So I think we can close this issue now.

**Comment by richstokes** [comment] 2020-02-21 18:57
Same issue here. Default Ubuntu install has no way to add a standalone node, since the projects directory and resources.xml file is not available. Is there another way?

**Comment by fdevans** [comment] 2020-04-08 21:58
There are options to add node via file source.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team

**Closed by fdevans** 2020-04-08 21:58 UTC
