### ISSUE TITLE
Can't change nodes on job without changing another option

### ISSUE THREAD

**Issue by dd5154** [rundeck/rundeck#4014] opened 2018-09-14 17:02 UTC
Can't change nodes on job without changing another option. I don't get an error in the GUI. If I change the nodes on the job and add or remove a word from the description of the job, the changed nodes will save.

My Rundeck detail

Rundeck version: 3.0.5.20180828-1
install type: rpm
OS Name/version: CentOS 7
DB Type/version: MariaDB 10.1.35-1
To Reproduce

Create a job with simple cmd step
Change the job to dispatch to a single node
Save job
Make sure jobs work
Change the node on the job
Save job
Node didn't save
Change the node on the job and change job description
Save job
Node did save

Desktop (please complete the following information):

OS: Mac OS
Browser chrome
Version 68.0.3440.106

**Comment by sjrd218** [comment] 2018-09-14 17:29
The root cause of this was address in a PR to fix #3920. This will be fixed in the next release.

**Comment by gtsteffaniak** [comment] 2018-09-14 19:52
same issue here on centos with 3.0.5

**Comment by gschueler** [comment] 2018-09-18 16:35
duplicate of https://github.com/rundeck/rundeck/issues/3920

**Closed by gschueler** 2018-09-18 16:35 UTC
