### ISSUE TITLE
[Feature Request] Run scheduled jobs with different options

### ISSUE THREAD

**Issue by gadelkareem** [rundeck/rundeck#1506] opened 2015-10-22 10:18 UTC
Currently Rundeck allows to schedule a job to run only if you have a "default" value for the options on the job. Would be great if we can specify the options on the schedular so it would run several times with different options, for ex: ( env:staging, env:prod...)

**Comment by LordMike** [comment] 2015-10-23 15:09
Maybe a job in general should have multiple triggers? (Much like Windows scheduled tasks)

**Comment by gschueler** [comment] 2015-10-23 16:23
dupe of https://github.com/rundeck/rundeck/issues/828

**Closed by gschueler** 2015-10-23 16:23 UTC
