### ISSUE TITLE
Killing job in progress does not kill child processes

### ISSUE THREAD

**Issue by richstokes** [rundeck/rundeck#5834] opened 2020-02-27 01:22 UTC
Howdy,

Not sure if this is expected behavior or not. 3.2.3-20200221 / Ubuntu 18

A job starts a script step which launches a long-running child process. We then kill the job. The child process continues to run in the background. IMO, killing the job should also kill child processes that it launched. Is this configurable?

**Comment by ProTip** [comment] 2020-02-27 02:16
Hi @richstokes,

This is a duplicate of #1038 . You can see my comment here https://github.com/rundeck/rundeck/issues/1038#issuecomment-461290416 for more information and workaround ideas.

**Closed by ProTip** 2020-02-27 02:16 UTC
