### ISSUE TITLE
Project name link goes back to Projects page - used to bring you to Jobs page

### ISSUE THREAD

**Issue by bman1978** [rundeck/rundeck#2275] opened 2017-01-12 14:52 UTC
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.1
* install type: launcher (rpm,deb,war,launcher)
* OS Name/version: Amazon Linux

**Expected Behavior**

When clicking on a Project name on the Project page, should bring you to jobs/home

**Actual Behavior**

the Link on the project goes to itself e.g. /project/AWS/home is the link on project name instead of project/AWS/jobs

**How to reproduce Behavior**

___

**Comment by gschueler** [comment] 2017-01-12 17:31
duplicate of #2168 fixed in 2.6.11 you can modify `rundeck.gui.startpage` config to change behavior

**Closed by gschueler** 2017-01-12 17:31 UTC
