### ISSUE TITLE
Configure user emails from LDAP

### ISSUE THREAD

**Issue by hmalinov** [rundeck/rundeck#1388] opened 2015-08-07 10:03 UTC
LDAP integration is nicely working, but user's email address is not configured through LDAP.
This way ${job.user.email} notification feature can not be used ( especially if you have a lot of users ).

**Comment by glennmcallister** [comment] 2015-10-08 15:18
Agreed. Asking potentially hundreds if not thousands of users to update their profile with the correct email address seems... challenging at best.

Configuration options like `use.user.email.from.ldap` and `update.existing.email.from.ldap` (I have no idea what the appropriate names would be, I don't recall the current config hierarchy) to first let email addresses be set from LDAP, and the second to let LDAP values override any existing values. Need to allow for changing email addresses for a given user, or to let the user override the setting. One of the settings has to win, and that is typically an organizational policy decision.

**Comment by ktosiek** [comment] 2015-11-24 16:13
See also #946

**Comment by gschueler** [comment] 2015-12-08 20:42
closing as dupe of #946

**Closed by gschueler** 2015-12-08 20:42 UTC
