### ISSUE TITLE
Scheduler status resets during recycle

### ISSUE THREAD

**Issue by ahonor** [rundeck/rundeck#1485] opened 2015-10-16 18:16 UTC
We recently discovered an issue when restarting Tomcat which involves the new Enable/Disable Schedule feature in 2.6.0. When restarting Tomcat, any unscheduled jobs are rescheduled. The job editor as well as the job xml state that the scheduler is disabled, but in reality it is enabled and will execute.

**Comment by gschueler** [comment] 2015-10-23 16:59
closing as dupe of #1475

**Closed by gschueler** 2015-10-23 16:59 UTC
Labels: bug
