### ISSUE TITLE
rd-jobs CLI password

### ISSUE THREAD

**Issue by mikeleigh** [rundeck/rundeck#1178] opened 2015-04-21 08:21 UTC
Using a non default password for the admin user causes rd-jobs to fail with authentication.  There does not appear to be an option to pass in the password or username to rd-jobs.

The following change replicates the error (substitute the md5_string_is_here for a real one):
`/etc/rundeck/realm.properties`
`admin: MD5:md5_string_is_here,user,admin,architect,deploy,build`

`root@rundeck.domain.local:~# rd-jobs -p PROJECT`
`Error: Error making server request to http://localhost:4440: Unable to authenticate user: admin`

Switching the password back to the default allows rd-jobs to complete
`/etc/rundeck/realm.properties`
`admin:admin,user,admin,architect,deploy,build`

`root@rundeck.domain.local:~# rd-jobs -p PROJECT`
`# Found 61 jobs:`
`- list of jobs ...`

**Comment by gschueler** [comment] 2015-04-21 23:54
the cli tools use the username/password defined in etc/framework.properties to authenticate.  this is going to change at some point

**Comment by gschueler** [comment] 2015-05-14 22:50
closing as dupe of #137

**Closed** 2015-05-15 19:16 UTC
Labels: enhancement
