### ISSUE TITLE
script-exec sometimes ssh's to the wrong IP address

### ISSUE THREAD

**Issue by davidleftwich** [rundeck/rundeck#2706] opened 2017-08-22 00:52 UTC
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.2
* install type: deb
* OS Name/version: Ubuntu 14.04.5
* DB Type/version: mysql 5.6.27

Configured to use ssh/scp to interact with nodes:
```
# replace jsch with ssh/scp
service.NodeExecutor.default.provider=script-exec
plugin.script-exec.default.command=/usr/bin/ssh -i ${project.ssh-keypath} ${node.username}@${node.hostname} ${exec.command}
plugin.script-exec.default.shell=bash -c
service.FileCopier.default.provider=script-copy
plugin.script-copy.default.command=/usr/bin/scp -q -i ${project.ssh-keypath} ${file-copy.file} ${node.username}@${node.hostname}:${file-copy.destination}
plugin.script-copy.default.shell=bash -c
plugin.script-copy.default.remote-filepath=${node.destdir}/${file-copy.filename}

```

**Expected Behavior**

Job executes on hundreds of nodes, using 50 threads. It uses script-copy to copy a simple shell script to each node and script-exec to execute it. This should work consistently (and does on my existing 2.5.2 install).

**Actual Behavior**

1-2 % of the time, script-exec ssh's to the wrong IP address, using the IP address of another node from the job. In the example below, 10.0.17.137 is the correct IP:

```
17:27:17        testnode         1. File        [workflow] beginExecuteNodeStep(testnode): NodeDispatch: ScriptFileItem{filepath='/var/lib/rundeck/tools/version-check.sh'}
17:27:17        testnode         1. File        [script-copy] executing: bash -c /usr/bin/scp -q -i /var/lib/rundeck/.ssh/rundeck /var/lib/rundeck/tools/version-check.sh lookerops@10.0.17.137:/tmp/1740-17-testnode-version-check.sh
17:27:17        testnode         1. File        [script-exec] executing: bash -c /usr/bin/ssh -i /var/lib/rundeck/.ssh/rundeck lookerops@10.0.17.137 chmod +x /tmp/1740-17-testnode-version-check.sh
17:27:18        testnode         1. File        [script-exec]: result code: 0, success: true
17:27:18        testnode         1. File        [script-exec] executing: bash -c /usr/bin/ssh -i /var/lib/rundeck/.ssh/rundeck lookerops@10.0.23.37 /tmp/1740-17-testnode-version-check.sh
17:27:19        testnode         1. File        bash: /tmp/1740-17-testnode-version-check.sh: No such file or directory
17:27:19        testnode         1. File        [script-exec]: result code: 127, success: false
17:27:19                        [script-exec]: result code: 127, success: false
17:27:19        testnode         1. File        [script-exec] executing: bash -c /usr/bin/ssh -i /var/lib/rundeck/.ssh/rundeck lookerops@10.0.17.137 rm -f /tmp/1740-17-testnode-version-check.sh
17:27:20        testnode         1. File        [script-exec]: result code: 0, success: true
17:27:20                        Failed: NonZeroResultCode: Result code was 127
17:27:20                        [workflow] finishExecuteNodeStep(testnode): NodeDispatch: NonZeroResultCode: Result code was 127
```

**How to reproduce Behavior**

It happens relatively rarely (on 1-2% of the nodes in any job), but it seems to happen every time I execute the job.

**Comment by davidleftwich** [comment] 2017-08-22 23:05
Seems related to the number of threads running concurrently. I haven't been able to reproduce it running single-threaded, but with 10 threads I can. With 50 threads it's even more common.

**Comment by james-8** [comment] 2017-09-08 13:29
Seen similar issue using custom script plugins (WorkflowNodeStep). RD_NODE_* environment vars and ${node.*} values are not guaranteed to correlate with the current node, when thread count greater than 1.

For custom script plugins, using plugin config items gets round this issue. But adds additional config compared to using RD_NODE_* variables within script, or passing ${node.*} values to script-args.

**My Rundeck detail**
Rundeck 2.9.3-1
RedHat 6.5
Installation method: RPM

**How to reproduce behavior**
Use following example plugin in job with thread count greater than 1.
plugin.yaml:
```
name: test
rundeckPluginVersion: 1.2
date: 7/9/2017
version: 1.0
providers:
    - name: test-workflow-nodestep
      service: WorkflowNodeStep
      plugin-type: script
      script-interpreter: /bin/bash
      script-file: TestScript
      script-args: ${node.hostname}
      config:
        - name: hostname
          type: String
          required: false
          scope: Instance
          renderingOptions:
            instance-scope-node-attribute: "hostname"
```

contents/TestScript:
```
#!/bin/bash
echo "RD_NODE_HOSTNAME:         $RD_NODE_HOSTNAME"
echo "node.hostname script arg: $1"
echo "via script config:        $RD_CONFIG_HOSTNAME"
```

**Expected behaviour**
RD_NODE_HOSTNAME and node.hostname to correlate with current node.

**Actual behaviour**
RD_NODE_HOSTNAME and node.hostname incorrect for some nodes (test-1 & test-2 in this example):
```
12:31:58    admin@test-3  RD_NODE_HOSTNAME:         test-3
12:31:58                  node.hostname script arg: test-3
12:31:58                  via script config:        test-3
12:31:58    admin@test-1  RD_NODE_HOSTNAME:         test-2
12:31:58                  node.hostname script arg: test-2
12:31:58                  via script config:        test-1
12:31:58    admin@test-2  RD_NODE_HOSTNAME:         test-3
12:31:58                  node.hostname script arg: test-3
12:31:58                  via script config:        test-2
```
On our setup, this occurs even with 2 hosts & 2 threads.

**Comment by gschueler** [comment] 2017-09-11 17:34
@james-8 thanks for a simple testcase

**Comment by james-8** [comment] 2017-10-05 09:55
Our setup has keybased authentication set at project level, but this is overridden by some nodes. In script plugin, node.ssh-authentication is observed to be set to password for nodes that are actually using project default (privateKey).

Assume this is related, in that the environment/node vars not correct for each node.

**Comment by doradojl** [comment] 2017-10-06 12:44
I have exactly the same issue, we are running 10 threats in parallel and the job takes closely to 3 minutes to finish. When Rundeck executes the first 10 in parallel some of them are executed for another node. The rest of them are being executed correctly because it works as a FIFO queue

**Comment by gschueler** [comment] 2017-10-11 22:15
believe this is also the same as #2756

**Comment by gschueler** [comment] 2017-10-13 23:06
I believe this bug is the same as #2756 and #2766 which is fixed in 2.9.4, please try the new release and verify

**Comment by davidleftwich** [comment] 2017-10-14 00:55
My test case (and a tougher one using script-copy and script-exec to run a simple script on 1500 instances with 100 threads) passes with 2.9.4. I'll start moving forward with my real work on 2.9.4, but from my tests, I consider this issue closed.

**Comment by gschueler** [comment] 2017-10-16 16:17
@davidleftwich good to hear, thanks

**Closed by gschueler** 2017-10-16 16:17 UTC
Labels: bug
