### ISSUE TITLE
Enforced Allowed values on option plugins cannot be used

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#4732] opened 2019-04-19 18:09 UTC
**Describe the bug**
Using an option plugin , it is not possible to use the "Enforced Allowed values" attribute on the option.

**My Rundeck detail**

* Rundeck version: 3.0.20
* install type: launcher
* OS Name/version: Mac OS 10.14
* DB Type/version: mysql

**To Reproduce**
1. Create or use an option plugin
2. Create a job with an option from the plugin
3. Select "Enforced Allowed values" 

**Expected behavior**
options values created with option plugins should allow the use of  "Enforced Allowed values" 

**Screenshots**
<img width="624" alt="Screenshot 2019-04-19 14 08 50" src="https://user-images.githubusercontent.com/6034968/56437262-b0b41680-62ac-11e9-9401-e2d53dede4bb.png">

<img width="625" alt="Screenshot 2019-04-18 15 04 52" src="https://user-images.githubusercontent.com/6034968/56437163-659a0380-62ac-11e9-91d2-ba2ffdbed97c.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14
 - Browser chrome
 - Version 73.0

**Comment by sjrd218** [comment] 2019-05-15 13:34
@ltamaster I think this got fixed with the fix for #4622. Can you confirm? I can't reproduce this issue.

**Comment by ltamaster** [comment] 2019-05-20 14:55
@sjrd218 I got the same issue on the last 3.1 build
<img width="591" alt="Screenshot 2019-05-20 10 54 36" src="https://user-images.githubusercontent.com/6034968/58031088-b8561d80-7aed-11e9-9222-3caf17176689.png">

**Comment by sjrd218** [comment] 2019-05-20 14:58
@ltamaster In the previous screenshot posted it doesn't appear that an option values plugin is begin used. The plugin should show up as an option to select in the `Allowed Values` section, and should be selected if it is being used.

**Comment by ltamaster** [comment] 2019-05-20 15:08
Yes that is also an issue, this is the previous
<img width="583" alt="Screenshot 2019-05-20 11 07 40" src="https://user-images.githubusercontent.com/6034968/58031946-85148e00-7aef-11e9-814f-5c83d73d7428.png">
 page

**Closed** 2019-05-24 00:53 UTC
