### ISSUE TITLE
Cross Architecture Docker Images

### ISSUE THREAD

**Issue by heywoodlh** [rundeck/rundeck#6496] opened 2020-09-25 21:56 UTC
**Is your feature request related to a problem? Please describe.**
The current [rundeck/rundeck](https://hub.docker.com/r/rundeck/rundeck) Docker image is only available for x86_64 bit.

**Describe the solution you'd like**
It would be nice if the containers were cross-architecture. I would love to be able to run RunDeck on an ARM devices such as a Raspberry Pi in Docker and I haven't seen any dependencies that were not available for ARM.

**Describe alternatives you've considered**
I'll probably just build my own Rundeck image that is cross-architecture in the meantime.

**Comment by fdevans** [comment] 2020-10-15 16:58
Duplicate of #6433 
Thanks for the request.  We can keep the conversation going on the referenced issue above.

**Closed by fdevans** 2020-10-15 16:58 UTC
