### ISSUE TITLE
Feature request: ability to select individual nodes when using variables/${options} as node filter arguments

### ISSUE THREAD

**Issue by Neutrollized** [rundeck/rundeck#3485] opened 2018-06-07 16:31 UTC
I'm trying to re-open #877. This was a request way back in 2014 in which ahonor had closed citing #2056...which is not the same thing.  #2056 just adds the ability to enable `Editable filter` in the job details, and that wasn't what was originally requested, so I'm here to hopefully be able to clarify what (I believe) the user was asking for, which in inline with what I'm asking for.

----------------------------------------------------

Currently, if a variable (e.g. ${option.project-id}) is used in the default Node filter filed in the Rundeck job details, you will get the following message when you run the job:

`The Node filters will be applied when the job is run.`
<img width="1143" alt="currently" src="https://user-images.githubusercontent.com/17765481/41112594-6b59414e-6a4d-11e8-8595-af3b2a6db109.png">

This is fine if i want to run it on all the nodes that meet that criteria, but what if i just want it to *LIST* these nodes so that I can select from the pool?

#2056 (Editable filters) didn't solve this:
<img width="1076" alt="editablefilters" src="https://user-images.githubusercontent.com/17765481/41112630-875d2432-6a4d-11e8-8f58-3dd331399778.png">

What I would like to see:
<img width="1065" alt="want" src="https://user-images.githubusercontent.com/17765481/41112578-5f696dc8-6a4d-11e8-83bb-18ff37f81abd.png">

**Comment by ahonor** [comment] 2018-06-07 16:36
@Neutrollized thanks for that clarification. That makes sense.

**Comment by ryancurrah** [comment] 2018-06-07 16:39
Subscribed. This would be a great enhancement.

**Comment by gschueler** [comment] 2019-09-17 21:01
Duplicate of #877

**Closed by gschueler** 2019-09-17 21:01 UTC
Labels: enhancement
