### ISSUE TITLE
Upgrading from 2.4.x to 2.6.x, all jobs have been set to "Enable Execution: no"

### ISSUE THREAD

**Issue by fseiftsmlb** [rundeck/rundeck#1483] opened 2015-10-16 16:51 UTC
We have 100's of jobs across dozens of projects, is there any way to do a mass job update and set all jobs to "Enable Execution: yes" ?

**Comment by ahonor** [comment] 2015-10-16 16:58
@fseiftsmlb we consider this a bug. As a workaround, you could use rd-jobs to dump out the job definitions and use something like xmlstarlet to rewrite that element to the desired value.

**Comment by ahonor** [comment] 2015-10-20 19:33
When jobs are being imported into a 2.6.x, the default should be enable execution: yes

**Comment by miguelantonio** [comment] 2015-10-21 03:45
@fseiftsmlb I'm not able to reproduce the bug, can you describe the sequence of the upgrade?

**Comment by gschueler** [comment] 2015-10-21 22:24
If I install 2.4/2.5.x then install 2.6, I do see the behavior:

* edit job
* Enable execution: no
* Enable schedule: no

however it doesn't seem to automatically disable the values.  Only upon editting the jobs will the radio button be set to the wrong value.  Added a fix for this in #1502 

If your upgrade caused some other kind of behavior, please let me know

**Closed** 2015-10-23 17:35 UTC
Labels: bug
