### ISSUE TITLE
Caught an exception, leaving main loop due to Socket closed

### ISSUE THREAD

**Issue by lmayorga1980** [rundeck/rundeck#699] opened 2014-03-08 00:31 UTC
Weird error trying to delete some files on a remote server. 
- NOPASSWD already set
- Default Requiretty - Commented already.

``` bash
[workflow] beginExecuteNodeStep(JIRA-PROD): NodeDispatch: com.dtolabs.rundeck.execution.ExecutionItemFactory$4@5b5caf
19:28:16            Using ssh keyfile: /Users/MYUSRNAME/.ssh/rundeck_key
19:28:16            Starting SSH Connection: lmo0@MYHOST (JIRA-PROD)
19:28:16            Set timeout to 0
19:28:16            Connecting to VAVP-PMO-ISU02:22
19:28:16            Connecting to VAVP-PMO-ISU02 port 22
19:28:16            Connection established
19:28:16            Remote version string: SSH-2.0-OpenSSH_4.3
19:28:16            Local version string: SSH-2.0-JSCH-0.1.50
19:28:16            CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
19:28:16            aes256-ctr is not available.
19:28:16            aes192-ctr is not available.
19:28:16            aes256-cbc is not available.
19:28:16            aes192-cbc is not available.
19:28:16            arcfour256 is not available.
19:28:16            CheckKexes: diffie-hellman-group14-sha1
19:28:16            diffie-hellman-group14-sha1 is not available.
19:28:16            SSH_MSG_KEXINIT sent
19:28:16            SSH_MSG_KEXINIT received
19:28:16            kex: server: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
19:28:16            kex: server: ssh-rsa,ssh-dss
19:28:16            kex: server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
19:28:16            kex: server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
19:28:16            kex: server: hmac-md5,hmac-sha1,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
19:28:16            kex: server: hmac-md5,hmac-sha1,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
19:28:16            kex: server: none,zlib@openssh.com
19:28:16            kex: server: none,zlib@openssh.com
19:28:16            kex: server: 
19:28:16            kex: server: 
19:28:16            kex: client: diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1
19:28:16            kex: client: ssh-rsa,ssh-dss
19:28:16            kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc
19:28:16            kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc
19:28:16            kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
19:28:16            kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
19:28:16            kex: client: none
19:28:16            kex: client: none
19:28:16            kex: client: 
19:28:16            kex: client: 
19:28:16            kex: server->client aes128-ctr hmac-md5 none
19:28:16            kex: client->server aes128-ctr hmac-md5 none
19:28:16            SSH_MSG_KEXDH_INIT sent
19:28:16            expecting SSH_MSG_KEXDH_REPLY
19:28:17            ssh_rsa_verify: signature true
19:28:17            Permanently added 'MYHOST' (RSA) to the list of known hosts.
19:28:17            SSH_MSG_NEWKEYS sent
19:28:17            SSH_MSG_NEWKEYS received
19:28:17            SSH_MSG_SERVICE_REQUEST sent
19:28:17            SSH_MSG_SERVICE_ACCEPT received
19:28:17            Authentications that can continue: publickey,password,keyboard-interactive
19:28:17            Next authentication method: publickey
19:28:17            Authentication succeeded (publickey).
19:28:17            Disconnecting from MYHOST port 22
19:28:17            Caught an exception, leaving main loop due to Socket closed
```

**Comment by kilsbo** [comment] 2015-11-26 13:48
In version 0.1.51 I get it in INFO level:

2015-11-26 13:37:38 INFO  jsch:36 - Caught an exception, leaving main loop due to Socket closed

Good to know not to worry about it though.

**Comment by rootAmeen** [comment] 2016-02-02 07:43
I'm having the same issue. The difference is when I run the command from node it goes without issues. When I run it inside a job in rundeck I get this error. What could be the cause?

**Comment by rootAmeen** [comment] 2016-02-02 08:03
After more debugging, I found that the command while running from the service takes around 10 seconds to complete. When I run it through rundeck it finishes within 1 second. Still trying to find root cause.

**Comment by tegansnyder** [comment] 2016-07-19 16:26
I also just experienced this issue. Any closure would be great.

**Comment by akashcha** [comment] 2017-05-21 00:08
Anything found on this issue?

**Comment by QtRoS** [comment] 2018-01-23 06:36
I have the same issue (but with GitLab & TeamCity).

**Comment by EugenMayer** [comment] 2018-04-05 12:02
same issue here.

The disconnects seems to be happening on a random point:

```

starting the drupal wiki stack
--
13:58:26 |   |   | Caught an exception, leaving main loop due to Read timed out
13:58:26 |   |   | Disconnecting from mariahilf.maintain.drupal-wiki.in port 2201
13:58:26 |   |   | Remote command failed with exit status -1
13:58:26 |   |   | Failed: NonZeroResultCode: Remote command failed with exit status -1
```

Interesting is, running to commands on the cli works and alson running the same command as the job executes using a one-off command in rundeck, works too. 

Is that a a bug within rundeck? using 2.10.8-1

**Comment by XiaoHuarong** [comment] 2019-01-15 07:45
**My code happen also, when I call command of jsch, Then displat this exception. How to work it out**

**Comment by iGajendraSingh** [comment] 2019-04-08 19:54
I'm facing same problem. Guys is there any solution?

**Comment by gschueler** [comment] 2019-09-17 20:37
I will close the issue. If you still have this problem, please re-open this issue.

**Closed by gschueler** 2019-09-17 20:37 UTC
Labels: status: out of date

**Comment by fuwj1994** [comment] 2020-08-06 02:04
The disconnects seems to be happening on a random point:

starting the our stack
--
13:58:26 |   |   | Caught an exception, leaving main loop due to Read timed out
13:58:26 |   |   | Disconnecting from x.x.x.x port 22
13:58:26 |   |   | Remote command failed with exit status -1
13:58:26 |   |   | Failed: NonZeroResultCode: Remote command failed with exit status -1
Interesting is, running to commands on the cli works and alson running the same command as the job executes using a one-off command in rundeck, works too.

Is that a a bug within rundeck? using 3.3.0

**Comment by mikeastevens** [comment] 2022-08-23 19:44
Interesting - issue faced by multiple people over a number of years and the tech closes the case as out of date.  What a tool.

**Comment by prosaikrish** [comment] 2023-01-20 03:27
I am getting the same error in ANT/scp

**Comment by syedfinclutech** [comment] 2023-09-18 13:45
I am getting the same error, it's 2023; anyone can suggest a solution?

**Comment by EugenMayer** [comment] 2023-09-18 16:18
@syedfinclutech considering the overall state of rundeck, the solution to the problem above seems to be https://saltproject.io/index.html (or any other).

Just to be clear, i'am using rundeck for 7 years now, so i'am not just ranting because 'i hate the tool' - since PageDuty bought rundeck, the entire ecosystem and strategy changed - and not for the better.
