### ISSUE TITLE
Feature Request: Force to select nodes before run the job

### ISSUE THREAD

**Issue by snebel29** [rundeck/rundeck#1188] opened 2015-04-23 16:56 UTC
Would by nice be able to select when you want to have all the nodes within "Change the target Nodes (x)" checked/unchecked by default for a job before run it, i find it usefull if you want to force people to select the nodes before run the job, for example:

You want to create a job to allow team members to restart some criticalservice in a cluster/farm of servers, but you don't want by default to have selected all the nodes to avoid restarting all the nodes always like default action and force the guy to think if he wants to run it on 1, 2 or all nodes.

**Comment by papagr** [comment] 2015-04-23 21:30
Hi everyone,

I also agree on that. There should be an option to display the nodes 
un-selected by default.

There is currently a workaround. Create an option, where the allowed 
values are the node names (without any defaults). Then use this option 
in the Node filter.

If the user does not select any nodes the job is not executed.

**Comment by snebel29** [comment] 2015-04-24 08:20
Hi papagr,
I'm trying to use this "work around" but i'm not able to use the option in the node filter, i did not find any help on documentation, did you tested it before? if yes can you explain me how to do it?

thanks in advance!

**Comment by pkr1234** [comment] 2015-04-24 14:00
Hello snebel29,

It is very easy to set it up.

1. I assume you have plenty of nodes in "Nodes".
2. Create an option called say NODEOPTION. You can make it multivalue (space separated)
3. In the option above, create a list of comma separated node names that matches your node in "Nodes" tab. Make sure you select "allow from list" and "non blank value". Save the option.
4. Select "Dispatch to Modes". In the filter type - ${option.NODEOPTION} 
5. Save


The reason it works is because ${option.NODEOPTION}  is space separated in multivalue which is fine for filtering node.

If you want you can have it pipe separated in multivalue and then use the filter as 
nodename:/${option.NODEOPTION}/

This works because it is a regular expression.

Hope this helps. The only downside is that you have to populate your NODEOPTION with all available nodes. 

Having said that, rundeck does have some glaring and basic omissions. This being one of them.

**Comment by snebel29** [comment] 2015-04-24 14:30
Hi,
I'm confused, when i try to do it under rundeck 2.3.2-1 i get this exception, what could it be?

java.util.regex.PatternSyntaxException: Illegal repetition near index 0
${option.NODEOPTION}
^
	at java.util.regex.Pattern.error(Pattern.java:1730)
	at java.util.regex.Pattern.closure(Pattern.java:2792)
	at java.util.regex.Pattern.sequence(Pattern.java:1906)
	at java.util.regex.Pattern.expr(Pattern.java:1769)
	at java.util.regex.Pattern.compile(Pattern.java:1477)
	at java.util.regex.Pattern.<init>(Pattern.java:1150)
	at java.util.regex.Pattern.compile(Pattern.java:840)
	at java.util.regex.Pattern.matches(Pattern.java:945)
	at java.lang.String.matches(String.java:2102)
	at com.dtolabs.rundeck.core.utils.NodeSet.matchRegexOrEquals(NodeSet.java:362)
	at com.dtolabs.rundeck.core.utils.NodeSet.matchesInput(NodeSet.java:255)
	at com.dtolabs.rundeck.core.utils.NodeSet$SetSelector.matchOrBlank(NodeSet.java:701)
	at com.dtolabs.rundeck.core.utils.NodeSet$SetSelector.matches(NodeSet.java:709)
	at com.dtolabs.rundeck.core.utils.NodeSet.shouldExclude(NodeSet.java:203)
	at com.dtolabs.rundeck.core.utils.NodeSet.acceptNode(NodeSet.java:92)
	at com.dtolabs.rundeck.core.common.NodeFilter.filterNodes(NodeFilter.java:35)
	at com.dtolabs.rundeck.core.common.Framework.filterNodeSet(Framework.java:528)
	at rundeck.services.FrameworkService$_filterNodeSet_closure4.doCall(FrameworkService.groovy:275)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at MetricswebGrailsPlugin$_addDynamicMetricMethods_closure26.doCall(MetricswebGrailsPlugin.groovy:174)
	at rundeck.services.FrameworkService.filterNodeSet(FrameworkService.groovy:274)
	at rundeck.controllers.ScheduledExecutionController._prepareExecute(ScheduledExecutionController.groovy:1554)
	at rundeck.controllers.ScheduledExecutionController$_closure8.doCall(ScheduledExecutionController.groovy:254)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:910)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:636)

**Comment by snebel29** [comment] 2015-04-24 14:35
I found how to "escape" it
hostname:/\Q${option.NODEOPTION}\E/

however i'm still having some anomalie but let me take a look first to be sure everything is fine :-)

**Comment by snebel29** [comment] 2015-04-24 14:52
No way, if i don't scape the reg expressioin i have all the time the "Illegal repetition near index 0" exception, if i scape it everything is fine until i try to run the job, when i obtain a "Not matched nodes" exception ... any ideas? could you provide me in some way a working job definition to load? :-)

**Comment by pkr1234** [comment] 2015-04-24 18:22
Hi,

If ${option.NODEOPTION} has special characters or characters that need escaping in regex, then you will get an exception. Do you have curly braces ({}) in your NODEOPTION values? That will cause a problem.

You can try without the regex instead like this in filter

hostname:${option.NODEOPTION}

(provided ${option.NODEOPTION} is a comma separated string}

http://rundeck.org/2.2.0/manual/node-filters.html

**Comment by papagr** [comment] 2015-04-24 20:25
On 24.04.2015 16:00, pkr1234 wrote:
>
> Hello snebel29,
>
> It is very easy to set it up.
>
>  1. I assume you have plenty of nodes in "Nodes".
>  2. Create an option called say NODEOPTION. You can make it multivalue
>     (space separated)
>  3. In the option above, create a list of comma separated node names
>     that matches your node in "Nodes" tab. Make sure you select "allow
>     from list" and "non blank value". Save the option.
>  4. Select "Dispatch to Modes". In the filter type - ${option.NODEOPTION}
>  5. Save
>

The above is what I am also doing.
>
> Hope this helps. The only downside is that you have to populate your 
> NODEOPTION with all available nodes.
>

Indeed, if you do not have many nodes is OK.
>
> Having said that, rundeck does have some glaring and basic omissions. 
> This being one of them.
>
I agree.

**Comment by snebel29** [comment] 2015-04-27 08:54
Hello,
There was no braces ({}) but i use "." dots may be it was the cause

By removing the slash "/" in the filter to do it without using regexpression works!

thank you so much both for the help

**Comment by gschueler** [comment] 2015-05-18 17:22
close as dupe of #114

**Closed by gschueler** 2015-05-18 17:22 UTC
