### ISSUE TITLE
Not able to connect to AD(VDS)

### ISSUE THREAD

**Issue by sankamuk** [rundeck/rundeck#3020] opened 2017-12-23 06:14 UTC
Issue type: Bug report/Enhancement Request

Defined the following in my profile.
-------------------------------------
JAAS_CONF="${JAAS_CONF:-$RDECK_CONFIG/jaas-ldap.conf}
LOGIN_MODULE="${LOGIN_MODULE:-ldap}

jaas-ldap.conf
-------------------------------------
ldap {
    com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
      debug = "true"
      ContextFactory = "com.sun.jndi.ldap.LdapCtxFactory"
      providerUrl = "ldaps://vds.company.com:636"
      bindDn = "CN=Some User,CN=Users,DC=eu,DC=company,DC=com"
      bindPassword = "MyPaSsWoRd"
      authenticationMethod="simple"
      forceBindingLogin="true"
      userBaseDn="dc=vds,DC=company,DC=com"
      userRdnAttribute="sAMAccountName"
      userIdAttribute="sAMAccountName"
      userPasswordAttribute="unicodePwd"
      userObjectClass="user"
      roleBaseDn="OU=Unix Groups,OU=Users,dc=vds,DC=company,DC=com"
      roleNameAttribute="cn"
      roleMemberAttribute="member"
      roleObjectClass="group"
      cacheDurationMillis="300000"
      reportStatistics="true";

};

Getting the below error:
-------------------------------------

2017-12-23 01:00:39.231:WARN:oejj.JAASLoginService:qtp1607521710-12:
javax.security.auth.login.LoginException: java.lang.NullPointerException|?at java.util.Hashtable.put(Hashtable.java:459)|?at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.getEnvironment(JettyCachingLdapLoginModule.java:928)|?at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.initialize(JettyCachingLdapLoginModule.java:813)|?at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)|?at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)|?at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)|?at java.lang.reflect.Method.invoke(Method.java:498)|?at javax.security.auth.login.LoginContext.invoke(LoginContext.java:736)|?at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)|?at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)|?at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)|?at java.security.AccessController.doPrivileged(Native Method)|?at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)|?at javax.security.auth.login.LoginContext.login(LoginContext.java:587)|?at org.eclipse.jetty.jaas.JAASLoginService.login(JAASLoginService.java:241)|?at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:52)|?at org.eclipse.jetty.security.authentication.FormAuthenticator.login(FormAuthenticator.java:192)|?at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:229)|?at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)|?at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)|?at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)|?at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)|?at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)|?at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)|?at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)|?at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)|?at org.eclipse.jetty.server.Server.handle(Server.java:446)|?at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)|?at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)|?at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)|?at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)|?at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)|?at java.lang.Thread.run(Thread.java:748)|
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:856)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.eclipse.jetty.jaas.JAASLoginService.login(JAASLoginService.java:241)
        at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:52)
        at org.eclipse.jetty.security.authentication.FormAuthenticator.login(FormAuthenticator.java:192)
        at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:229)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:446)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:748)

**My Rundeck detail**

* Rundeck version: 2.9.3-1.37
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version: Linux 3.10.0-327.36.3.el7.x86_64
* DB Type/version: H2

**Expected Behavior**
To connect to RunDeck and authenticate via AD(VDS)

**How to Reproduce**

**Comment by gschueler** [comment] 2018-01-04 22:45
try changing 

    ContextFactory = "com.sun.jndi.ldap.LdapCtxFactory" 

to this (lowercase `contextFactory`:

    contextFactory = "com.sun.jndi.ldap.LdapCtxFactory"

**Comment by sankamuk** [comment] 2018-01-09 17:03
Thanks so much for help. I see it is able to connect but it throws new exception

2018-01-09 11:46:41.537:DBUG:cdrjj.JettyCachingLdapLoginModule:qtp1607521710-68: Cache Miss for myid.
2018-01-09 11:46:41.537:DBUG:cdrjj.JettyCachingLdapLoginModule:qtp1607521710-68: Searching for users with filter: '(&(objectClass={0})({1}={2}))' from base dn: dc=vds,DC=company,DC=com
2018-01-09 11:46:41.681:DBUG:cdrjj.JettyCachingLdapLoginModule:qtp1607521710-68: Found user?: true
2018-01-09 11:46:41.682:INFO:cdrjj.JettyCachingLdapLoginModule:qtp1607521710-68: Attempting authentication: CN=myid,OU=Admin Accounts,OU=Accounts,OU=Users,OU=ZZ PAM,DC=eu,DC=company,DC=com
javax.naming.NoPermissionException: [LDAP: error code 50 - Insufficient Access Rights]; remaining name 'OU=Unix Groups,OU=Users,DC=eu,DC=company,DC=com'

**When i have already updated my group**

**--- Added in jaas-ldap.conf**
supplementalRoles="myADGroup"

**--- in web.xml**
<role-name>myADGroup</role-name>

**--- in admin.aclpolicy**

description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job:
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: myADGroup

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: myADGroup

Is there a working model i can follow.

**Comment by sjrd218** [comment] 2019-03-21 15:14
@sankamuk The last error you are reporting is your LDAP server telling you that the user you have configured to bind to your LDAP server doesn't have enough privileges on the LDAP server to do the requested action. You would need to add sufficient permissions in your LDAP server for the bind user to do searches on your directory. I will close this issue since the problem is not in Rundeck.

**Closed by sjrd218** 2019-03-21 15:14 UTC
