### ISSUE TITLE
java.lang.NullPointerException in RundeckAPICentralDispatcher.deleteStoredJobs

### ISSUE THREAD

**Issue by dpetzel** [rundeck/rundeck#1349] opened 2015-07-20 15:30 UTC
When attempting to purge jobs we are seeing the following exception and the jobs are not purged

```
$ rd-jobs purge -p "MyProject" -g "MyGroup"
WARN  SimpleHttpConnectionManager: SimpleHttpConnectionManager being used incorrectly.  Be sure that HttpMethod.releaseConnection() is always called and that only one thread and/or method is using this connection manager at a time.
java.lang.NullPointerException
	at com.dtolabs.client.services.RundeckAPICentralDispatcher.deleteStoredJobs(RundeckAPICentralDispatcher.java:1182)
	at com.dtolabs.rundeck.core.cli.jobs.JobsTool.purgeAction(JobsTool.java:817)
	at com.dtolabs.rundeck.core.cli.jobs.JobsTool.go(JobsTool.java:647)
	at com.dtolabs.rundeck.core.cli.BaseTool.run(BaseTool.java:108)
	at com.dtolabs.rundeck.core.cli.jobs.JobsTool.main(JobsTool.java:383)
Error: null
```
I've tried running as root as well as the rundeck user and get the same result.

What is interesting is that the server on which I get this error is part of a clustered configuration. I have tried it on both nodes without success.

When running the same command on a standalone instance the command runs cleans. 

We are running 2.4.0. I poked around https://github.com/rundeck/rundeck/blob/v2.4.0/core/src/main/java/com/dtolabs/client/services/RundeckAPICentralDispatcher.java#L1182 but nothing really jumped out at me. Unfortunately, I'm not in a position where I can test the latest version in a clustered fashion.

**Comment by gschueler** [comment] 2015-07-20 16:38
rundeck version, 2.4.0?

**Comment by dpetzel** [comment] 2015-07-20 16:43
Correct. I also found the following in the rundeck.log which might help

```
2015-07-20 08:19:50,168 [qtp254432682-35] ERROR org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver - MySQLIntegrityConstraintViolationException occurred when processing request: [POST] /api/5/jobs/delete
Cannot delete or update a parent row: a foreign key constraint fails (`mydb`.`rdoption`, CONSTRAINT `FKAFFFA9275C4E2579` FOREIGN KEY (`scheduled_execution_id`) REFERENCES `scheduled_execution` (`id`)). Stacktrace follows:
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`mydb`.`rdoption`, CONSTRAINT `FKAFFFA9275C4E2579` FOREIGN KEY (`scheduled_execution_id`) REFERENCES `scheduled_execution` (`id`))
```

**Comment by gschueler** [comment] 2015-07-20 16:49
i see this previous issue which did not have any resolution, was unable to reproduce: https://github.com/rundeck/rundeck/issues/374

are you able to delete the jobs via the GUI?

**Comment by dpetzel** [comment] 2015-07-20 16:54
I am able to delete the jobs via the GUI. I did a single delete, as well as a bulk delete. In the UI though I can't delete everything in the group (I need to select each item). Thats probably sufficient for what I need to delete today, but some our groups are pretty large so having the ability to do a complete group would be extremely helpful

**Comment by gschueler** [comment] 2015-07-20 16:56
@dpetzel bulk delete is available in later versions

**Comment by dpetzel** [comment] 2015-07-20 16:58
@gschueler not sure I follow, I have the bulk delete option already, its just that the UI doesn't let you select a group (and automatically select all its children) whereas the rd-purge command does.

Are you saying in later versions the UI will let you select just the group and delete all the children?

**Comment by gschueler** [comment] 2015-07-20 16:59
@dpetzel sorry, my mistake, I was thinking 2.4.0 was missing bulk delete. it's a good enhancement request to be able to select all in a group

**Comment by dpetzel** [comment] 2015-07-20 17:01
@gschueler no worries, the select all actually works as well (After I select the group), so I'm able to delete fairly easily, but I think the issue that is outstanding is that rd-jobs purge doesn't work correctly (which is a fairly low priority for me since I can navigate the UI for the task at hand today).

**Comment by dpetzel** [comment] 2015-07-20 17:03
I spoke to soon..... I am able to recreate in the UI as well...

```
Cannot delete or update a parent row: a foreign key constraint fails (`rundeck_db_qa`.`rdoption`, CONSTRAINT `FKAFFFA9275C4E2579` FOREIGN KEY (`scheduled_execution_id`) REFERENCES `scheduled_execution` (`id`))
```

I navigate to the top level group, hit bulk delete, do a select all, and hit hit delete. This produces (in the UI):
```
Cannot delete or update a parent row: a foreign key constraint fails (`mydb`.`rdoption`, CONSTRAINT `FKAFFFA9275C4E2579` FOREIGN KEY (`scheduled_execution_id`) REFERENCES `scheduled_execution` (`id`))
```

I have a theory that one of my jobs in this group is setup on a schedule. I'll see if I can chase down that theory to help narrow things down.

**Comment by dpetzel** [comment] 2015-07-20 17:29
So I did narrow this error down to a single job in that group. I'm actually unable to delete that one job by any measure. Looking at the job (and the history of the yaml in scm) I doesn't appear it is or ever was setup on a schedule.

**Comment by dpetzel** [comment] 2015-07-20 17:34
I can't explain why... but on that problem job I edit it and removed all the options (based on the reference to the rdoption table) and I was able to delete it after that.

**Comment by gschueler** [comment] 2016-07-06 20:51
closing: no update

**Closed by gschueler** 2016-07-06 20:51 UTC
