### ISSUE TITLE
jobs never complete in 2.5.0

### ISSUE THREAD

**Issue by ko-christ** [rundeck/rundeck#1190] opened 2015-04-27 07:01 UTC
Jobs never complete in 2.5.0-1.6.GA (CentOS 7.1)
Bug does not exist in version 2.4.2-1.3.GA

Sample job yaml 
https://paste.kde.org/pxtqoba9t

**Comment by scottwarren** [comment] 2015-04-28 00:16
:+1:

**Comment by robgott** [comment] 2015-04-28 06:25
updated from 2.2.1-0 to 2.5.0-1 and experiencing the same issue
happens when running any kind of job including an adhoc command

`Red Hat Enterprise Linux Server release 6.5 (Santiago)`
`Linux 2.6.32-431.5.1.el6.x86_64 #1 SMP Fri Jan 10 14:46:43 EST 2014 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by danifr** [comment] 2015-04-28 07:40
Have you checked this?
https://github.com/rundeck/rundeck/issues/1179

**Comment by robgott** [comment] 2015-04-28 07:53
hi @danifr looks like it could be the same issue, I can see the SQL error however I'm using the built in H2 DB though so will have to figure out how to alter the columns on that.

**Comment by gschueler** [comment] 2015-05-13 17:26
I believe this is a dupe of #1179 closing for now

**Closed by gschueler** 2015-05-13 17:26 UTC
