### ISSUE TITLE
Is autoReconnect=true still a thing for RD 3.x?

### ISSUE THREAD

**Issue by benruset** [rundeck/rundeck#4638] opened 2019-03-19 14:23 UTC
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 3.0.16-20190223 
* install type: (rpm,deb,war,launcher?) RPM
* OS Name/version: Amazon Linux AMI release 2017.09
* DB Type/version: MySQL 5.6.40 through Amazon RDS

**Expected Behavior**
JDBC honoring the ?autoReconnect=true parameter in the MySQL URL

**How to Reproduce**
I've had several long running jobs fail with the error "Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 37,657,120 milliseconds ago.  The last packet sent successfully to the server was 37,657,121 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem."

however my MySQL connection URL looks like this: dataSource.url = jdbc:mysql://rdsname.rds.amazonaws.com/database?autoReconnect=true

**Comment by tanji** [comment] 2019-03-21 15:53
autoReconnect in MySQL connector/J does not really work anymore and is deprecated. It should be removed from the docs.
As for the loss of connection it should be handled in the application itself. As the docs say:
> The use of this feature is not recommended, because it has side effects related to session state and data consistency when applications don't handle SQLExceptions properly, and is only designed to be used when you are unable to configure your application to handle SQLExceptions resulting from dead and stale connections properly.

to rundeck maintainers I think that is an important fix to be made in 3.0.

**Comment by ProTip** [comment] 2019-03-22 00:04
Hi @benruset ,

It's often unnecessary once Rundeck has bootstrapped because the tomcat connection pool will handle reconnects. However, if the database is not available Rundeck will fail to bootstrap and crash.

I believe what you are seeing is unrelated to reconnects and has to do with a Transaction being open on a stale connection. Is your job running for over 10 hours? Does your job include a reference to another job?

Thanks!

**Comment by benruset** [comment] 2019-03-22 00:27
Thanks for getting back to me.

The database is an AWS RDS instance running in the same AZ as the EC2 instance running Rundeck, so access to the database ought to be speedy.

The job runs anywhere from 8-10 hours and during most of that time the running script does not have any output. But the log shows the output the script makes when it ends.

The job doesn't reference any other job. It's completely standalone.

**Comment by ProTip** [comment] 2019-03-22 00:36
Thanks for info!

I believe the quick "fix" may be to raise the `wait_timeout` on the RDS instance. MySQL's default is typically 8 hours, but this could be raised higher than you expect the job to take.

Would you be able to post a sanitized YAML export of your job? We may be able to use this and an artificially low `wait_timeout` to reproduce the issue and find the root cause.

**Comment by ProTip** [comment] 2019-03-27 19:14
Hi @benruset ,

I believe this is a duplicate of #4459 and has been fixed for release `3.0.19` in #4654 (more details as to the issue in that PR). Increasing the wait_timeout should work, however the fix will hopefully make that redundant.

**Closed by ProTip** 2019-03-27 19:14 UTC
