### ISSUE TITLE
Oracle config error

### ISSUE THREAD

**Issue by trfeldmann** [rundeck/rundeck#676] opened 2014-02-26 15:39 UTC
After configuring the oracle rdb connection, the server fails to create tables with this error:

ERROR hbm2ddl.SchemaUpdate  - ORA-01754: a table may contain only one column of type LONG

Here is oracle's explanation of this:
http://stackoverflow.com/questions/13582213/why-oracle-allows-only-one-long-column-per-table

**Comment by jquick** [comment] 2015-02-26 01:41
I recently did a quick work around by just manually creating the tables with a script. I just changed the "long" -> "clob" and "long raw" -> "blob". There may be a better way but its working fine. 

Here is the script I used to create them incase anyone else has the same issue:
http://pastebin.com/NDYt518T

**Comment by trfeldmann** [comment] 2015-02-27 15:33
Thank you very much Greg.  Will using this option be supported under our
Rundeck Pro contract?

**Comment by hipslu** [comment] 2015-05-20 11:55
version 2.5 seems to add new tables - is there an updated version available? thank you very much!

**Comment by jquick** [comment] 2015-05-28 01:20
It looks like they added 2 new tables in 2.5. They should both work with Oracle out of the box:

    desc PROJECT
    Name         Null     Type               
    ------------ -------- ------------------ 
    ID           NOT NULL NUMBER(19)         
    VERSION      NOT NULL NUMBER(19)         
    DATE_CREATED NOT NULL TIMESTAMP(6)       
    DESCRIPTION           VARCHAR2(255 CHAR) 
    LAST_UPDATED NOT NULL TIMESTAMP(6)       
    NAME         NOT NULL VARCHAR2(255 CHAR) 

    desc ORCHESTRATOR
    Name    Null     Type               
    ------- -------- ------------------ 
    ID      NOT NULL NUMBER(19)         
    VERSION NOT NULL NUMBER(19)         
    CONTENT          LONG()             
    TYPE    NOT NULL VARCHAR2(255 CHAR) 

If you want peak performance you can alter ORCHESTRATOR and set "CONTENT" to clob after.

**Comment by ikogan** [comment] 2016-02-02 21:15
In an effort to be a bit more forward-proof, we setup a custom hibernate dialect:

```java
package edu.ohio.ais.hibernate.dialect;

import org.hibernate.dialect.Oracle10gDialect;

import java.sql.Types;

/**
 * Custom Oracle dialect that fixes various issues with
 * Oracle support in Hibernate.
 */
public class OhioOracleDialect extends Oracle10gDialect {
    protected void registerLargeObjectTypeMappings() {
        registerColumnType( Types.BINARY, 2000, "raw($l)" );
        registerColumnType( Types.BINARY, "long raw" );

        registerColumnType( Types.VARBINARY, 2000, "raw($l)" );
        registerColumnType( Types.VARBINARY, "long raw" );

        registerColumnType( Types.BLOB, "blob" );
        registerColumnType( Types.CLOB, "clob" );

        registerColumnType( Types.LONGVARCHAR, "clob" );
        registerColumnType( Types.LONGVARBINARY, "long raw" );
    }
}
```

The major change is the `Types.LONGVARCHAR` registration. The original dialect simply does `long`.

**Comment by predatorx** [comment] 2016-04-20 03:47
Is this issue still present? I am getting the same error when I try to use rundeck with Oracle 11g DB. Rundeck version is 2.6.6-1. Is there a easy location from which we can get the SQLs so that we can fix and run? I tried to find them but could not find the SQL files.

**Comment by ikogan** [comment] 2016-04-20 03:51
There isn't SQL that'll fix this. You need to create a custom `jar` file that contains something like the above class and reference that class as your Hibernate dialect.

**Comment by predatorx** [comment] 2016-04-28 16:46
Thanks iKogan. For now I have used the SQL queries from the http://pastebin.com/NDYt518T. Will check the custom jar approach.

**Comment by lamxung55** [comment] 2016-07-09 07:16
Where can I change type from LONG to CLOB????
I'm using rundeck-launcher-2.6.8.jar

**Comment by jquick** [comment] 2016-08-26 17:55
@ikogan do you mind stating how you got this to work. I created a jar file based on your template above, and I am able to include it in another test java file without issue. I dropped the jar file into the rundeck bootstrap so it gets picked up in the paths and loaded. I then updated the config file accordingly and it /tries/ to load the new dialect but complains about not finding the "org.hibernate.dialect.Oracle10gDialect". I am pretty sure this is included already since we can use it by default so I am not sure if I'm loading my stuff to early or what. I even tried including the hibernate jar as well but ran into more issues. Thanks for your help!

**Comment by ikogan** [comment] 2016-08-26 18:02
We didn't put it in bootstrap. In a standard install based on the Rundeck RPM, we have it in `/var/lib/rundeck/exp/webapp/WEB-INF/lib/ohio-commons-hibernate-oracle-1.0.0.jar`.

It's been a while since I had to set this up but I believe that I tried several places, and the one we settled on is the only one that would get picked up.

**Comment by jquick** [comment] 2016-08-26 18:36
@ikogan you are amazing! Dropping it in there worked like a charm. If anyone else is having issues I created a generic jar you can use and also steps to take here:
https://github.com/jquick/rundeck_oracle_dialect

**Comment by silverfisk** [comment] 2016-09-01 07:19
great, thanks @ikogan! :+1:

**Comment by jdesmet** [comment] 2016-09-08 01:43
This issue deserves a proper fix: the use of Oracle is documented. Looking at the logfiles eyeballing the tables that are attempted to be created, the fields affected should neither be `CLOB` or `LONG` anyhow. By simply avoiding both cases we can have a better implementation. It seems to me that a sufficiently big sized `VARCHAR` will cover. 

`CLOB` and `LONG` are treated very differently on databases - in the case of Oracle it can cause the field to be stored on dedicated table separate from the original. This will negatively affect the database.
I think it is ok, to xxx on a field-size of `VARCHAR2(50)` for something like a `node_include_os_version`, or `VARCHAR2(2000)` for something like `adhoc_filepath`.

There were just poor design choices made causing a poor schema to be created (or in the case of Oracle an invalid one). Anyone attempting just to replace `LONG` with `CLOB` will just trade one bad for another.

Maybe these design choices are not as bad for MySQL or HSQLDB. Maybe 'support' for Oracle should be simply dropped?

**Comment by admun** [comment] 2017-02-17 18:40
any update on this? I just got hit by this issue.

**Comment by admun** [comment] 2017-02-17 19:03
@jquick I tried your rundeck dialect on 2.7.2 and it's failed with

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [com.rundeck.hibernate.RundeckOracleDialect] as strategy [org.hibernate.dialect.Dialect]

**Comment by ikogan** [comment] 2017-02-17 19:29
Where did you put the jar file?

**Comment by admun** [comment] 2017-02-18 00:04
The same lib/ directory where the rest of things are:

javax.servlet-3.0.0.v201112011016.jar  jetty-security-9.0.7.v20131107.jar  log4j-1.2.16.jar
jetty-all-9.0.7.v20131107.jar          jetty-server-9.0.7.v20131107.jar    not-yet-commons-ssl-0.3.11.jar
jetty-http-9.0.7.v20131107.jar         jetty-util-9.0.7.v20131107.jar      ojdbc6.jar
jetty-io-9.0.7.v20131107.jar           jna-3.2.2.jar                       rundeck-jetty-server-2.7.2.jar
jetty-jaas-9.0.7.v20131107.jar         libpam4j-1.5.jar                    rundeck-oracle-dialect.jar

**Comment by jquick** [comment] 2017-02-18 17:50
on my install those look to be the bootstrap jars:
`/var/lib/rundeck/bootstrap/`
You have to put it deeper here:
`/var/lib/rundeck/exp/webapp/WEB-INF/lib`

ones around it should look like:
```
-rw-r--r-- 1 root root 1211862 Aug  3  2016 rundeck-core-2.6.9.jar
-rw-r--r-- 1 root root     956 Oct  6 16:51 rundeck-oracle-dialect.jar
-rw-r--r-- 1 root root   20432 Aug  3  2016 rundeck-storage-api-2.6.9.jar
-rw-r--r-- 1 root root   15689 Aug  3  2016 rundeck-storage-conf-2.6.9.jar
-rw-r--r-- 1 root root   10311 Aug  3  2016 rundeck-storage-data-2.6.9.jar
-rw-r--r-- 1 root root   13602 Aug  3  2016 rundeck-storage-filesys-2.6.9.jar
````

**Comment by admun** [comment] 2017-02-20 19:40
hum... I am still seeing the error after I put the  rundeck-oracle-dialect.jar in rundeck/exp/webapp/WEB-INF/lib.

weird thing is I saw that jar disappeared after I start rundeck....

org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [com.rundeck.hibernate.RundeckOracleDialect] as strategy [org.hibernate.dialect.Dialect]

**Comment by jquick** [comment] 2017-02-21 13:28
Very odd, I recently upgraded our test boxes to 2.7.2 and they are working as expected. Can you change the ownership to root? I think this is the default for the deb package and make it so the rundeck process cant redo them. I suspect you are using the jar version or something else which may flash this folder on boot.

**Comment by admun** [comment] 2017-02-21 16:43
ah!

That might explain it.

I am using the rundeck-launcher-2.7.2.jar. So, all the other jars are not used at all in that case?

So, is that a way to run this w/ rundeck-launcher?

Thanks for the help

**Comment by jquick** [comment] 2017-02-23 18:15
yeah i dont think it will work in libext thats for like plugins. I am not sure how to configure this with the jar version having never used it myself. My only guess would be to mess with the permissions so it cant remove it.

**Comment by kishorej** [comment] 2017-10-13 03:30
I am trying to install Rundeck 2.9.3 with Oracle DB and using starting with java -jar run*.jar and gettting the below error. Could you please anyone help to resolve this issue.

2017-10-13 03:24:02,197 [main] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:788)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:434)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:780)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:284)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1322)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:732)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:490)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118)
        at org.eclipse.jetty.server.Server.start(Server.java:342)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60)
        at org.eclipse.jetty.server.Server.doStart(Server.java:290)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
        at com.dtolabs.rundeck.RunServer.run(RunServer.java:119)
        at com.dtolabs.rundeck.RunServer.main(RunServer.java:79)
        at com.dtolabs.rundeck.ExpandRunServer.invokeMain(ExpandRunServer.java:752)
        at com.dtolabs.rundeck.ExpandRunServer.execute(ExpandRunServer.java:709)
        at com.dtolabs.rundeck.ExpandRunServer.run(ExpandRunServer.java:309)
        at com.dtolabs.rundeck.ExpandRunServer.main(ExpandRunServer.java:113)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
        ... 20 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
        ... 20 more
Caused by: java.lang.NullPointerException
        ... 20 more

**Comment by gschueler** [comment] 2019-05-20 22:00
I will close the issue. If you still have this problem, please re-open this issue.

**Closed by gschueler** 2019-05-20 22:00 UTC
Labels: bug

**Comment by fasoares** [comment] 2019-10-29 23:24
Hi Guys.

I'm config a brand new  Rundeck 3.1.2 with Oracle 11g and I'm getting this error when Rundeck starts and create/update the table schema:

Configuring Spring Security Core ...
... finished configuring Spring Security Core

[2019-10-29 15:16:08.983]  WARN ExceptionHandlerLoggedImpl --- [           main] GenerationTarget encountered exception accepting command : Error executing DDL via JDBC Statement

org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlString(AbstractSchemaMigrator.java:524)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlStrings(AbstractSchemaMigrator.java:470)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.createTable(AbstractSchemaMigrator.java:273)
	at org.hibernate.tool.schema.internal.GroupedSchemaMigratorImpl.performTablesMigration(GroupedSchemaMigratorImpl.java:71)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.performMigration(AbstractSchemaMigrator.java:203)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:110)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:176)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:65)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:478)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:423)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:711)
	at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSessionFactory(HibernateMappingContextConfiguration.java:276)
	at org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory.create(HibernateConnectionSourceFactory.java:86)
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:39)
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:23)
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:64)
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:52)
	at org.grails.datastore.mapping.core.connections.ConnectionSourcesInitializer.create(ConnectionSourcesInitializer.groovy:24)
	at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:201)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:648)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:145)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getSingletonFactoryBeanForTypeCheck(AbstractAutowireCapableBeanFactory.java:928)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:805)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:573)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:432)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:395)
	at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:206)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1260)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1094)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1072)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:225)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:703)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:527)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:84)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:393)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:380)
	at grails.boot.GrailsApp$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at rundeckapp.Application.main(Application.groovy:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00984: column not allowed here

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:210)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:30)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:931)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1150)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1792)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1745)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:334)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy81.execute(Unknown Source)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54)
	... 83 common frames omitted

It appears that some script is trying to manipulate a data (insert) and putting a wrong value in a column. But I don't have any clue what table is it.

Anyone got the same error as me?
