### ISSUE TITLE
Enable use of multiple rundeck-config property files

### ISSUE THREAD

**Issue by ahonor** [rundeck/rundeck#1311] opened 2015-07-01 19:42 UTC
Allow administrators the ability to separate configuration settings by concern e.g. (datasource-config.properties, email-config.properties, etc) as comma separated list of files.

Profile can be edited to contain the `rundeck.config.locations`  system property to point to the file list. e.g.: `-Drundeck.config.locations=file1,file2,file3`

**Comment by gschueler** [comment] 2015-10-07 22:47
dupe of #1339

**Closed by gschueler** 2015-10-07 22:47 UTC
Labels: configuration, enhancement
