### ISSUE TITLE
Disabled Job and Disabled Schedule not honored 

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6357] opened 2020-08-10 14:10 UTC
I have a job which I had disabled the schedule and execution since last week but the job continues to execute...

![image](https://user-images.githubusercontent.com/20629911/89791607-63c70580-dad8-11ea-856d-266324b4a576.png)

![image](https://user-images.githubusercontent.com/20629911/89791666-73dee500-dad8-11ea-8e9b-d92ed09249ae.png)

RUNDECK
APIVERSION : 35
BASE : /var/lib/rundeck
BUILD : 3.3.1-20200727
BUILDGIT : v3.3.1-0-g7716cc7
SERVERUUID :
VERSION : 3.3.1-20200727

**Comment by MegaDrive68k** [comment] 2020-08-10 16:49
Confirmed.
Steps to reproduce:

1. Create a job, like this:

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>da9b58e6-7de3-4d7a-ab1f-0401d892df5f</id>
    <loglevel>INFO</loglevel>
    <name>HelloWorld</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <schedule>
      <month month='*' />
      <time hour='*' minute='*' seconds='0/5' />
      <weekday day='*' />
      <year year='*' />
    </schedule>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "hi"</exec>
      </command>
    </sequence>
    <uuid>da9b58e6-7de3-4d7a-ab1f-0401d892df5f</uuid>
  </job>
</joblist>
```

2. Check the execution, works as expects.

3. Edit the job and set "Enable Scheduling" -> No and "Enable Execution?" -> No

4. The job keeps executing following the schedule crontab.

Thanks for your feedback @hs-hub-world!

**Comment by tazou** [comment] 2020-08-25 06:02
Hello,
Same issue here in 3.3.2 version.
Regards.

**Comment by tazou** [comment] 2020-09-01 07:14
To precise my previous post, I have for example a daily job, then I disable the cron like this (picture) and save the job.
The next day the job is still start by rundeck automatically.
![image](https://user-images.githubusercontent.com/6482957/91813783-7cd45980-ec33-11ea-90a1-3864836c761c.png)

**Comment by goodwillcoding** [comment] 2020-09-17 18:50
Can confirm this as well. Experiencing an exact same problem. Seems to be no way to disable a job.

**Comment by goodwillcoding** [comment] 2020-09-18 16:21
@MegaDrive68k is there any sense when this bug will be addressed?

**Comment by PedroRossi** [comment] 2020-09-23 14:40
@goodwillcoding you can download the job yaml, edit the `scheduleEnabled` to false and upload the yaml again to disable the job and do the opposite to enable again. It is really boring having to do this, but at least it works.

**Comment by goodwillcoding** [comment] 2020-09-23 16:53
> @goodwillcoding you can download the job yaml, edit the `scheduleEnabled` to false and upload the yaml again to disable the job and do the opposite to enable again. It is really boring having to do this, but at least it works.

Just tested this and it does NOT work for me :(

**Comment by goodwillcoding** [comment] 2020-09-23 16:53
> @goodwillcoding you can download the job yaml, edit the `scheduleEnabled` to false and upload the yaml again to disable the job and do the opposite to enable again. It is really boring having to do this, but at least it works.

@PedroRossi Just tested this and it does NOT work for me :(

**Comment by goodwillcoding** [comment] 2020-09-23 16:57
The only thing that works seems to be disabling the job and restarting rundeckd service. My guess that stops the scheduled threads. It's a terrible work around though.

**Comment by goodwillcoding** [comment] 2020-09-23 16:58
@MegaDrive68k anything at all on estimate when this will be fixed?

**Comment by PedroRossi** [comment] 2020-09-23 17:07
@goodwillcoding which version of Rundeck are you using? I am using 3.3.0 (Docker) and this worked fine, maybe there is another catch in other versions.

**Comment by goodwillcoding** [comment] 2020-09-23 17:09
@PedroRossi 3.3.3

**Comment by gschueler** [comment] 2020-09-23 23:26
I believe a workaround is to choose "Disable Schedule" or "Disable Execution" from the dropdown menu or job bulk edit menu in the jobs list.  This correctly toggles scheduling for scheduled jobs.

**Closed** 2020-09-24 22:45 UTC
Labels: bug, status:reproduced
