### ISSUE TITLE
Error execution powershell scripts

### ISSUE THREAD

**Issue by vidalsysadmin** [rundeck/rundeck#4602] opened 2019-03-08 11:00 UTC
**Describe the bug**
Script powershell is executed over ssh on Windows node, but the scripts. So the job never stop and don't execute next step. I execute scripts locally on the server, it runs and exit correctly. 

**My Rundeck detail**
* Rundeck version: 3.0.13
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: mariadb 5.5.60

**To Reproduce**
1. Install openssh on Windows node
2. Create a job that execute a script powershell thanks this command : "powershell.exe -executionpolicy bypass -File 'path/script.ps1'"
3. Execute the job
4. The job never stop because it doesn't exit from script powershell

**Expected behavior**
The powershell script have to exit correctly and the job have to execute next steps.

**Comment by ltamaster** [comment] 2019-04-11 17:37
Hi @vidalsysadmin 

I wasn't able to reproduce it.
It worked for me with a windows server 2012 and cygwin+ssh

Can you share further information about the issue? 
For example the node definition and project settings.

<img width="732" alt="Screenshot 2019-04-11 13 36 01" src="https://user-images.githubusercontent.com/6034968/55978829-c6975b00-5c5e-11e9-9bc7-da26a451cc5a.png">
<img width="1052" alt="Screenshot 2019-04-11 13 36 10" src="https://user-images.githubusercontent.com/6034968/55978830-c72ff180-5c5e-11e9-9c92-a4c61200bcde.png">

**Comment by hgoalv18** [comment] 2019-11-11 12:09
I have the same problem. Any solution?

I have rundeck installed with a mysql backend.

I have a job that run a powershell script over ssh an never stop, but the job work fine.

**Comment by fdevans** [comment] 2020-04-08 22:23
Going to close this since there hasn't been any feedback for while.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team

**Closed by fdevans** 2020-04-08 22:23 UTC
