### ISSUE TITLE
Bug: job takeover

### ISSUE THREAD

**Issue by pchevallereau** [rundeck/rundeck#3225] opened 2018-03-27 08:40 UTC
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.1
* install type: deb
* OS Name/version: Ubuntu 16 server 
* DB Type/version: mariadb

**Expected Behavior**
Hi, 

Sometimes i have a problem with the job takeover, the job is lock and he don't want to switch to the new server.

Command:
` 
data="<takeoverSchedule><server all=\"true\"/><job id=\"${job_id}\"/></takeoverSchedule>"
curl -H Content-Type:application/xml -H "${api_token}" --data "${data}" -X PUT http://"${server}:${port}"/api/21/scheduler/takeover
`

Error:
`        <pre>java.sql.SQLException: Lock wait timeout exceeded; try restarting transaction
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
        at rundeck.services.ScheduledExecutionService$_claimScheduledJob_closure10.doCall(ScheduledExecutionService.groovy:438)
        at rundeck.services.ScheduledExecutionService.claimScheduledJob(ScheduledExecutionService.groovy:432)
        at rundeck.services.ScheduledExecutionService$_claimScheduledJobs_closure11$_closure109.doCall(ScheduledExecutionService.groovy:529)
        at rundeck.services.ScheduledExecutionService$_claimScheduledJobs_closure11.doCall(ScheduledExecutionService.groovy:488)
        at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:815)
        at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:715)
        at rundeck.services.ScheduledExecutionService.claimScheduledJobs(ScheduledExecutionService.groovy:486)
        at rundeck.services.ScheduledExecutionService.reclaimAndScheduleJobs(ScheduledExecutionService.groovy:741)
        at rundeck.controllers.ScheduledExecutionController.apiJobClusterTakeoverSchedule(ScheduledExecutionController.groovy:4262)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:582)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:74)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:540)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:446)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:748)`

**How to Reproduce**
I don't know because it don't crash systematically, note: a restart of all servers from cluster unlock the job

**Comment by jtobard** [comment] 2018-03-27 19:16
Hi @pchevallereau I wasn't able to reproduce the error, can you paste here the output of this command:
`SHOW ENGINE INNODB STATUS` 
To get more information about what statement cause the deadlock.
(See: https://mariadb.com/kb/en/library/show-engine-innodb-status/ )

**Comment by pchevallereau** [comment] 2018-03-28 15:53
Hi @jtobard, 
i will try this when the error once more appears !

Thank for your help!

**Comment by pchevallereau** [comment] 2018-03-29 14:07
Hi @jtobard 

Here is, the result of `SHOW ENGINE INNODB STATUS` when the command waiting before crashing:

At the middle:
`| InnoDB |      |
=====================================
2018-03-29 15:55:50 0x7f324c1e3700 INNODB MONITOR OUTPUT
=====================================
Per second averages calculated from the last 24 seconds
-----------------
BACKGROUND THREAD
-----------------
srv_master_thread loops: 499117 srv_active, 0 srv_shutdown, 4387711 srv_idle
srv_master_thread log flush and writes: 4885766
----------
SEMAPHORES
----------
OS WAIT ARRAY INFO: reservation count 13312482
OS WAIT ARRAY INFO: signal count 9446754
RW-shared spins 0, rounds 1320337, OS waits 631657
RW-excl spins 0, rounds 1656151, OS waits 85414
RW-sx spins 52177, rounds 1297337, OS waits 21370
Spin rounds per wait: 1320337.00 RW-shared, 1656151.00 RW-excl, 24.86 RW-sx
------------
TRANSACTIONS
------------
Trx id counter 14354628
Purge done for trx's n:o < 14352236 undo n:o < 0 state: running but idle
History list length 863
LIST OF TRANSACTIONS FOR EACH SESSION:
---TRANSACTION 421329039787336, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 421329039784624, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 421329039783720, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 14354627, ACTIVE 49 sec starting index read
mysql tables in use 4, locked 4
LOCK WAIT 2 lock struct(s), heap size 1136, 1 row lock(s)
MySQL thread id 23498685, OS thread handle 139853739476736, query id 391747531 150.60.67.86 rundeck updating
update scheduled_execution set version=159787, arg_string=null, date_created='2017-12-08 10:28:56', day_of_month='?', day_of_week='*', description='0 0/1 * ? * * * /var/www/PR/plugin/shell/purge_memory.sh', do_nodedispatch=1, exec_count=10, execution_enabled=1, filter='ute.*', group_path=null, hour='*', job_name='purge_memory.sh', last_updated='2018-03-29 15:55:09', log_output_threshold=null, log_output_threshold_action='halt', log_output_threshold_status=null, loglevel='INFO', minute='0/1', month='*', multiple_executions=1, next_execution='2018-03-29
Trx read view will not see trx with id >= 14354595, sees < 14352259
------- TRX HAS BEEN WAITING 41 SEC FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 66 page no 8 n bits 112 index PRIMARY of table `rundeckdb`.`scheduled_execution` trx id 14354627 lock_mode X locks rec but not gap waiting
Record lock, heap no 31 PHYSICAL RECORD: n_fields 63; compact format; info bits 0
 0: len 8; hex 8000000000000036; asc        6;;
 1: len 6; hex 000000daff80; asc       ;;
 2: len 7; hex 3a00000294082b; asc :     +;;
 3: len 8; hex 800000000002702a; asc       p*;;
 4: SQL NULL;
 5: len 5; hex 999e50a738; asc   P 8;;
 6: len 1; hex 3f; asc ?;;
 7: len 1; hex 2a; asc *;;
 8: len 30; hex 3020302f31202a203f202a202a202a202f7661722f7777772f5554452f70; asc 0 0/1 * ? * * * /var/www/PR/p; (total 70 bytes);
 9: len 1; hex 01; asc  ;;
 10: len 8; hex 800000000000000a; asc         ;;
 11: len 1; hex 01; asc  ;;
 12: len 5; hex 7574652e2a; asc ute.*;;
 13: SQL NULL;
 14: len 1; hex 2a; asc *;;
 15: len 30; hex 64625f7574652d6c61706f7374655f70757267655f656e76656c6f707065; asc purge_enveloppe; (total 43 bytes);
 16: len 5; hex 999f7af206; asc   z  ;;
 17: SQL NULL;
 18: len 4; hex 68616c74; asc halt;;
 19: SQL NULL;
 20: len 4; hex 494e464f; asc INFO;;
 21: len 3; hex 302f31; asc 0/1;;
 22: len 1; hex 2a; asc *;;
 23: len 1; hex 01; asc  ;;
 24: len 5; hex 999f7af240; asc   z @;;
 25: SQL NULL;
 26: SQL NULL;
 27: SQL NULL;
 28: SQL NULL;
 29: SQL NULL;
 30: SQL NULL;
 31: len 1; hex 01; asc  ;;
 32: SQL NULL;
 33: len 1; hex 00; asc  ;;
 34: SQL NULL;
 35: SQL NULL;
 36: SQL NULL;
 37: SQL NULL;
 38: SQL NULL;
 39: SQL NULL;
 40: SQL NULL;
 41: len 1; hex 01; asc  ;;
 42: SQL NULL;
 43: len 1; hex 01; asc  ;;
 44: len 4; hex 8000270f; asc   ' ;;
 45: len 1; hex 01; asc  ;;
 46: SQL NULL;
 47: len 12; hex 7369652d6c6f63616c5f6462; asc Projet1;;
 48: SQL NULL;
 49: SQL NULL;
 50: len 1; hex 01; asc  ;;
 51: len 1; hex 01; asc  ;;
 52: len 1; hex 30; asc 0;;
 53: len 30; hex 61626133343165622d316537612d346366362d613365332d653633373738; asc aba341eb-1e7a-4cf6-a3e3-e63778; (total 36 bytes);
 54: len 1; hex 01; asc  ;;
 55: SQL NULL;
 56: SQL NULL;
 57: len 8; hex 800000000001025e; asc        ^;;
 58: len 4; hex 726f6f74; asc root;;
 59: len 30; hex 6275696c642c6172636869746563742c726f6f742c61646d696e2c757365; asc build,architect,root,admin,use; (total 38 bytes);
 60: len 30; hex 63333165376234332d363138372d346232342d616537322d663263383137; asc c31e7b43-6187-4b24-ae72-f2c817; (total 36 bytes);
 61: len 8; hex 8000000000023db8; asc       = ;;
 62: len 1; hex 2a; asc *;;

------------------
---TRANSACTION 14354565, ACTIVE 50 sec inserting
mysql tables in use 4, locked 4
LOCK WAIT 7 lock struct(s), heap size 1136, 2 row lock(s), undo log entries 4
MySQL thread id 23498653, OS thread handle 139853738264320, query id 391732163 150.60.67.87 rundeck update
insert into execution (version, abortedby, arg_string, cancelled, date_completed, date_started, do_nodedispatch, execution_type, failed_node_list, filter, loglevel, node_exclude, node_exclude_name, node_exclude_os_arch, node_exclude_os_family, node_exclude_os_name, node_exclude_os_version, node_exclude_precedence, node_exclude_tags, node_filter_editable, node_include, node_include_name, node_include_os_arch, node_include_os_family, node_include_os_name, node_include_os_version, node_include_tags, node_keepgoing, node_rank_attribute, node_rank_order_ascending, node_threadcount, orchestrator_id,
Trx read view will not see trx with id >= 14354562, sees < 14352259
------- TRX HAS BEEN WAITING 50 SEC FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 66 page no 8 n bits 112 index PRIMARY of table `rundeckdb`.`scheduled_execution` trx id 14354565 lock mode S locks rec but not gap waiting
Record lock, heap no 31 PHYSICAL RECORD: n_fields 63; compact format; info bits 0
 0: len 8; hex 8000000000000036; asc        6;;
 1: len 6; hex 000000daff80; asc       ;;
 2: len 7; hex 3a00000294082b; asc :     +;;
 3: len 8; hex 800000000002702a; asc       p*;;
 4: SQL NULL;
 5: len 5; hex 999e50a738; asc   P 8;;
 6: len 1; hex 3f; asc ?;;
 7: len 1; hex 2a; asc *;;
 8: len 30; hex 3020302f31202a203f202a202a202a202f7661722f7777772f5554452f70; asc 0 0/1 * ? * * * /var/www/PR/p; (total 70 bytes);
 9: len 1; hex 01; asc  ;;
 10: len 8; hex 800000000000000a; asc         ;;
 11: len 1; hex 01; asc  ;;
 12: len 5; hex 7574652e2a; asc ute.*;;
 13: SQL NULL;
 14: len 1; hex 2a; asc *;;
 15: len 30; hex 64625f7574652d6c61706f7374655f70757267655f656e76656c6f707065; asc purge_enveloppe; (total 43 bytes);
 16: len 5; hex 999f7af206; asc   z  ;;
 17: SQL NULL;
 18: len 4; hex 68616c74; asc halt;;
 19: SQL NULL;
 20: len 4; hex 494e464f; asc INFO;;
 21: len 3; hex 302f31; asc 0/1;;
 22: len 1; hex 2a; asc *;;
 23: len 1; hex 01; asc  ;;
 24: len 5; hex 999f7af240; asc   z @;;
 25: SQL NULL;
 26: SQL NULL;
 27: SQL NULL;
 28: SQL NULL;
 29: SQL NULL;
 30: SQL NULL;
 31: len 1; hex 01; asc  ;;
 32: SQL NULL;
 33: len 1; hex 00; asc  ;;
 34: SQL NULL;
 35: SQL NULL;
 36: SQL NULL;
 37: SQL NULL;
 38: SQL NULL;
 39: SQL NULL;
 40: SQL NULL;
 41: len 1; hex 01; asc  ;;
 42: SQL NULL;
 43: len 1; hex 01; asc  ;;
 44: len 4; hex 8000270f; asc   ' ;;
 45: len 1; hex 01; asc  ;;
 46: SQL NULL;
 47: len 12; hex 7369652d6c6f63616c5f6462; asc Projet1;;
 48: SQL NULL;
 49: SQL NULL;
 50: len 1; hex 01; asc  ;;
 51: len 1; hex 01; asc  ;;
 52: len 1; hex 30; asc 0;;
 53: len 30; hex 61626133343165622d316537612d346366362d613365332d653633373738; asc aba341eb-1e7a-4cf6-a3e3-e63778; (total 36 bytes);
 54: len 1; hex 01; asc  ;;
 55: SQL NULL;
 56: SQL NULL;
 57: len 8; hex 800000000001025e; asc        ^;;
 58: len 4; hex 726f6f74; asc root;;
 59: len 30; hex 6275696c642c6172636869746563742c726f6f742c61646d696e2c757365; asc build,architect,root,admin,use; (total 38 bytes);
 60: len 30; hex 63333165376234332d363138372d346232342d616537322d663263383137; asc c31e7b43-6187-4b24-ae72-f2c817; (total 36 bytes);
 61: len 8; hex 8000000000023db8; asc       = ;;
 62: len 1; hex 2a; asc *;;

------------------
---TRANSACTION 14352259, ACTIVE 2869 sec
2 lock struct(s), heap size 1136, 1 row lock(s)
MySQL thread id 23491951, OS thread handle 139853739173632, query id 391773935 150.60.67.86 rundeck cleaning up
Trx read view will not see trx with id >= 14352235, sees < 14352235
--------
FILE I/O
--------
I/O thread 0 state: waiting for completed aio requests (insert buffer thread)
I/O thread 1 state: waiting for completed aio requests (log thread)
I/O thread 2 state: waiting for completed aio requests (read thread)
I/O thread 3 state: waiting for completed aio requests (read thread)
I/O thread 4 state: waiting for completed aio requests (read thread)
I/O thread 5 state: waiting for completed aio requests (read thread)
I/O thread 6 state: waiting for completed aio requests (write thread)
I/O thread 7 state: waiting for completed aio requests (write thread)
I/O thread 8 state: waiting for completed aio requests (write thread)
I/O thread 9 state: waiting for completed aio requests (write thread)
Pending normal aio reads: [0, 0, 0, 0] , aio writes: [0, 0, 0, 0] ,
 ibuf aio reads:, log i/o's:, sync i/o's:
Pending flushes (fsync) log: 0; buffer pool: 0
522717 OS file reads, 18219135 OS file writes, 4250636 OS fsyncs
0.00 reads/s, 0 avg bytes/read, 0.00 writes/s, 0.00 fsyncs/s
-------------------------------------
INSERT BUFFER AND ADAPTIVE HASH INDEX
-------------------------------------
Ibuf: size 1, free list len 11, seg size 13, 1267 merges
merged operations:
 insert 737, delete mark 1222, delete 41
discarded operations:
 insert 0, delete mark 0, delete 0
Hash table size 69257, node heap has 1 buffer(s)
Hash table size 69257, node heap has 1 buffer(s)
Hash table size 69257, node heap has 2 buffer(s)
Hash table size 69257, node heap has 0 buffer(s)
Hash table size 69257, node heap has 100 buffer(s)
Hash table size 69257, node heap has 1 buffer(s)
Hash table size 69257, node heap has 101 buffer(s)
Hash table size 69257, node heap has 1 buffer(s)
884.92 hash searches/s, 379.36 non-hash searches/s
---
LOG
---
Log sequence number 14075740284
Log flushed up to   14075740284
Pages flushed up to 14075740284
Last checkpoint at  14075740275
0 pending log flushes, 0 pending chkp writes
1821101 log i/o's done, 0.00 log i/o's/second
----------------------
BUFFER POOL AND MEMORY
----------------------
Total large memory allocated 275120128
Dictionary memory allocated 234507
Buffer pool size   16384
Free buffers       1024
Database pages     15153
Old database pages 5573
Modified db pages  0
Percent of dirty pages(LRU & free pages): 0.000
Max dirty pages percent: 75.000
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
Pages made young 4228380, not young 56842661
0.00 youngs/s, 0.00 non-youngs/s
Pages read 522659, created 39242, written 15615978
0.00 reads/s, 0.00 creates/s, 0.00 writes/s
Buffer pool hit rate 1000 / 1000, young-making rate 0 / 1000 not 0 / 1000
Pages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s
LRU len: 15153, unzip_LRU len: 0
I/O sum[166]:cur[0], unzip sum[0]:cur[0]
--------------
ROW OPERATIONS
--------------
0 queries inside InnoDB, 0 queries in queue
3 read views open inside InnoDB
Process ID=30518, Main thread ID=139853052241664, state: sleeping
Number of rows inserted 2894400, updated 1753448, deleted 1167294, read 169740334572
0.00 inserts/s, 0.00 updates/s, 0.00 deletes/s, 632.10 reads/s
Number of system rows inserted 0, updated 0, deleted 0, read 0
0.00 inserts/s, 0.00 updates/s, 0.00 deletes/s, 0.00 reads/s
----------------------------
END OF INNODB MONITOR OUTPUT
============================
`
Thanks

**Comment by pchevallereau** [comment] 2018-03-30 10:44
ERROR message in service.log

ERROR ScheduledExecutionService: claimScheduledJob: failed for 54 on node 0e31d231-bf61-4894-bd4b-237801e9181d: locking failure

**Comment by pchevallereau** [comment] 2018-04-04 10:59
@jtobard have you found something?

**Comment by jtobard** [comment] 2018-04-04 12:28
@pchevallereau I see on the logs that `insert into execution` waits for 50 seconds `---TRANSACTION 14354565, ACTIVE 50 sec inserting`, and if I'm reading correctly your job runs every minute. ¿Do you have indexes created on the tables?

**Comment by pchevallereau** [comment] 2018-04-04 12:36
@jtobard  Yes the job was executed every minute, no index on this tables

**Comment by jtobard** [comment] 2018-04-04 12:44
That explains why the table is locked on the takeover, you should consider creating some index on the table o purge the execution history for performance.

**Comment by pchevallereau** [comment] 2018-04-04 12:48
MariaDB [rundeckdb]> SHOW INDEX FROM scheduled_execution;
+---------------------+------------+------------------------------+--------------+-----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table               | Non_unique | Key_name                     | Seq_in_index | Column_name     | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+---------------------+------------+------------------------------+--------------+-----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| scheduled_execution |          0 | PRIMARY                      |            1 | id              | A         |          54 |     NULL | NULL   |      | BTREE      |         |               |
| scheduled_execution |          0 | UK_4t4ehlssm8lvaxieybr42ow5x |            1 | uuid            | A         |          54 |     NULL | NULL   | YES  | BTREE      |         |               |
| scheduled_execution |          1 | FK_mns7yxw0cx9msuk59x9f2b4lv |            1 | orchestrator_id | A         |           2 |     NULL | NULL   | YES  | BTREE      |         |               |
| scheduled_execution |          1 | FK_jln7b7a683uwkl4fg6kpacqnp |            1 | workflow_id     | A         |          54 |     NULL | NULL   | YES  | BTREE      |         |               |
+---------------------+------------+------------------------------+--------------+-----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
4 rows in set (0.00 sec)

**Comment by pchevallereau** [comment] 2018-04-04 12:50
Return of show index in mariadb:

![image](https://user-images.githubusercontent.com/20992504/38308435-60f639ae-3817-11e8-8ff3-610cd10f0351.png)

You think something missing?

**Comment by pchevallereau** [comment] 2018-04-04 13:00
@jtobard, i think the request crash because the primary key column "id" already have an id 66

**Comment by pchevallereau** [comment] 2018-04-04 14:04
@gschueler you have an idea?

**Comment by jtobard** [comment] 2018-04-18 15:50
@pchevallereau I was unable to reproduce this issue, I populate my execution table and run jobs each minute but never got a deadlock on the job takeover API call.
¿There's any other information about this job you can give us to try to reproduce it?

**Comment by pchevallereau** [comment] 2018-04-19 07:12
Hi @jtobard,

I don't have any other informations about this,
but last week, i have update my rundeck to the latest version, and delete database to switch to a new one.

Today, i try to reproduce it but it don't appear. 
Maybe the old database was corrupted.

**Comment by jtobard** [comment] 2018-04-19 11:58
@pchevallereau I'm going to close this case, feel free to reopen it if it happens again and have any new information about it

**Closed by jtobard** 2018-04-19 11:58 UTC
