### ISSUE TITLE
SCM import fails

### ISSUE THREAD

**Issue by ChiefAlexander** [rundeck/rundeck#1854] opened 2016-05-20 21:03 UTC
Version: 2.6.7-1 cafe bonbon goldenrod plane
I have setup SCM with our internal github repo to import jobs. I am able to see the diffs on commits that I have made but when trying to import I get the following error.

```
An Error Occurred
org/rundeck/plugin/scm/git/imp/actions/ImportJobs$_getInputView_closure1

Error Details 
Request: /project/alva_dev/job/6bba2829-6c3c-4df1-a55c-839ef9d19830/scm/import/performAction?actionId=import-all
Message: org/rundeck/plugin/scm/git/imp/actions/ImportJobs$_getInputView_closure1 
Caused by: Executing action [performAction] of controller [rundeck.controllers.ScmController] caused exception: Runtime error executing action 
Class: ScmController 
At Line: [1034] 
Code Snippet:

Stack Trace
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [performAction] of controller [rundeck.controllers.ScmController]  caused exception: Runtime error executing action
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
    at org.eclipse.jetty.server.Server.handle(Server.java:349)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:910)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
    ... 46 more
Caused by: java.lang.reflect.InvocationTargetException
    ... 46 more
Caused by: java.lang.NoClassDefFoundError: org/rundeck/plugin/scm/git/imp/actions/ImportJobs$_getInputView_closure1
    at org.rundeck.plugin.scm.git.imp.actions.ImportJobs.getInputView(ImportJobs.groovy:27)
    at org.rundeck.plugin.scm.git.GitImportPlugin.getInputViewForAction(GitImportPlugin.groovy:387)
    at rundeck.services.ScmService.getImportInputView(ScmService.groovy:215)
    at rundeck.services.ScmService.getInputView(ScmService.groovy:198)
    at rundeck.controllers.ScmController.performAction(ScmController.groovy:1034)
    ... 46 more

Rundeck © Copyright 2016 #SimplifyOps. All rights reserved. Licenses 2.6.7-1 cafe bonbon goldenrod plane
```

**Comment by ahonor** [comment] 2016-05-24 14:19
@ChiefAlexander was this an upgraded rundeck install? I wonder if there is a conflict between versions.

**Comment by ChiefAlexander** [comment] 2016-05-24 14:36
Yes, I believe we have gone from 2.6.4 -> 2.6.7 using the webtrends cookbook as our upgrade method

**Comment by gschueler** [comment] 2016-05-24 23:44
@ChiefAlexander can you check if there are multiple versions of the git plugin in the libext dir?

**Comment by ChiefAlexander** [comment] 2016-05-25 13:15
@gschueler only one version is present, rundeck-git-plugin-2.6.7.jar

**Comment by gschueler** [comment] 2016-07-18 17:26
plugin jar loading was improved to avoid conflicts for #1898 , so this may be fixed with that

**Comment by ChiefAlexander** [comment] 2016-07-18 18:50
We have created a new instance using a mysql backend service and a load balanced frontend and have not had the same issue crop up. It could be that our original instance had some funkiness because of our testing or maybe because of the upgrade we did. I still have our original instance up and it still has the same behavior, if you would like us to do any testing on it quickly.

**Comment by gschueler** [comment] 2016-07-18 23:17
hmm, not sure if there's a way to test it in-situ like that. Running the latest code and seeing or not seeing the same problem would really be the best way to confirm it.

**Comment by isuftin** [comment] 2016-08-24 14:00
I am also seeing this issue. 

Rundeck 2.6.9 on CentOS 6.7. Using rundeck-git-plugin-2.6.9.jar. Created the instance on August 3rd. 

When attempting to commit to GitHub SCM, seeing:

```
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [performAction] of controller [rundeck.controllers.ScmController]  caused exception: Runtime error executing action
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:58)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:910)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:191)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
	... 49 more
Caused by: java.lang.reflect.InvocationTargetException
	... 49 more
Caused by: java.lang.NoClassDefFoundError: org/rundeck/plugin/scm/git/exp/actions/CommitJobsAction$_getInputView_closure1
	at org.rundeck.plugin.scm.git.exp.actions.CommitJobsAction.getInputView(CommitJobsAction.groovy:33)
	at org.rundeck.plugin.scm.git.GitExportPlugin.getInputViewForAction(GitExportPlugin.groovy:116)
	at rundeck.services.ScmService.getExportInputView(ScmService.groovy:207)
	at rundeck.services.ScmService.getInputView(ScmService.groovy:196)
	at rundeck.controllers.ScmController.performAction(ScmController.groovy:1034)
	... 49 more
```

**Comment by seunaw** [comment] 2016-09-16 20:41
I am running into the same issue, I am using Rundeck 2.6.9-1 on Centos 7.2, using rundeck-git-plugin-2.6.9.jar. 

Does anyone have any updates regarding this issue?

**Comment by gschueler** [comment] 2016-09-16 20:44
I have not reproduced this issue.  Is there a sequence of actions that triggers this reliably?

**Comment by seunaw** [comment] 2016-09-16 20:57
@gschueler 
Mine is actually due to an export not an import. My steps are 

- Click on project
- Click "Commit Changes to Git" under "Job Actions" dropdown.

![image](https://cloud.githubusercontent.com/assets/5809894/18600968/37712374-7c15-11e6-9a18-580fe68aabf6.png)

**Comment by gschueler** [comment] 2016-09-16 21:56
strange.  you only have one rundeck-git plugin in the libext dir?  Is this right after restarting rundeck, or after it runs for a while?
what OS/version JDK vendor/version ?

**Comment by seunaw** [comment] 2016-09-16 22:07
I found the issue.  I had two versions of java installed  java-1.7.0 and
 java-1.8.0 on my CentOS Linux release 7.2.1511 (Core).

I removed java-1.8.0 and now it works.

**Comment by gschueler** [comment] 2017-03-07 18:36
same issues: #2031 and #2294

**Comment by gschueler** [comment] 2017-03-07 18:36
related https://github.com/rundeck/rundeck/issues/1785#issuecomment-265814468

**Closed** 2017-03-10 23:11 UTC
Labels: bug
