### ISSUE TITLE
SqlExceptionHelper - Data truncation: Data too long for column 'succeeded_node_list' after upgrade to 2.7.1

### ISSUE THREAD

**Issue by schast** [rundeck/rundeck#2288] opened 2017-01-22 12:59 UTC
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.1
* install type: launcher
* OS Name/version: Red Hat Enterprise Linux Server release 6.6 (Santiago)

**Actual Behavior**
after upgrade from 2.6.11 to 2.7.1 some jobs with many nodes does not stop running after job is finished or failed.

Error in the var/log/service.log:
```
2017-01-22 13:27:04,442 ERROR ExecutionUtilService - Execution failed: 340496 in project am-admin: [Workflow result: , step failures: {1=Dispatch failed on 3 nodes: [my_really_really_long_node_name_01: ConnectionFailure: [jsch-scp] Failed copying the file: Connection refused (Connection refused), my_really_really_long_node_name_02: ConnectionFailure: [jsch-scp] Failed copying the file: Connection refused (Connection refused), my_really_really_long_node_name_03: SSHProtocolFailure: connection is closed by foreign host]}, Node failures: {my_really_really_long_node_name_01=[ConnectionFailure: [jsch-scp] Failed copying the file: Connection refused (Connection refused)], my_really_really_long_node_name_02=[ConnectionFailure: [jsch-scp] Failed copying the file: Connection refused (Connection refused)], my_really_really_long_node_name_03=[SSHProtocolFailure: connection is closed by foreign host]}, status: failed]
2017-01-22 13:27:04,524 ERROR SqlExceptionHelper - Data truncation: Data too long for column 'succeeded_node_list' at row 1
2017-01-22 13:27:04,537 ERROR ExecutionJob - Execution 340496 save result status: caught exception: Hibernate operation: could not execute statement; SQL [n/a]; Data truncation: Data too long for column 'succeeded_node_list' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'succeeded_node_list' at row 1
org.springframework.dao.DataIntegrityViolationException: Hibernate operation: could not execute statement; SQL [n/a]; Data truncation: Data too long for column 'succeeded_node_list' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'succeeded_node_list' at row 1
        at rundeck.services.ReportService.reportExecutionResult(ReportService.groovy:65)
        at rundeck.services.ExecutionService.logExecution(ExecutionService.groovy:843)
        at rundeck.services.ExecutionService$_saveExecutionState_closure61.doCall(ExecutionService.groovy:2227)
        at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2148)
        at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:509)
        at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:447)
        at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:519)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:162)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:90)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:89)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'succeeded_node_list' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3833)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
        ... 13 more
2017-01-22 13:27:04,538 WARN  ExecutionJob - Execution 340496 save result status: failed (attempts=1/10), retrying in 6839ms
```

**Temporary solution**
the mysql database table **base_report** has a column **succeeded_node_list** with size **varchar(255)**.
after setting this to **longtext** (as in the table **execution**) the problem no longer occurs.
`ALTER TABLE base_report MODIFY succeeded_node_list longtext;`

**Comment by jamieps** [comment] 2017-01-23 00:10
This is a duplicate of #2228; that is not the only column affected, it'll be resolved in the next release.

**Closed** 2017-01-23 05:59 UTC
