### ISSUE TITLE
timeout in job; rundeck doesn't retry

### ISSUE THREAD

**Issue by bdmorin** [rundeck/rundeck#1079] opened 2015-01-21 14:05 UTC
I have a Workflow setup to push a build to our jetty server. The jetty startup script (the default) has some kind of issue where the terminal won't let go and rundeck gets stuck in a notty. So while I'm working on this situation, I figure I'll set a timeout value, and have the job retry. I have logic in the startup job that if it's already running, it considers the job successful.

When I was testing the job by itself, I would set a timeout value of 30 seconds, and rundeck would kill the job and all remaining steps; without performing a retry. I had everything set to retry, I allowed it, and had a value of 3 for the max retrys. As soon as rundeck hit the timeout value it didn't perform any retrys and didn't perform any of the rest of the steps in the job. 

My question is "Is this behavior intentional?". Is there a way to timeout just 1 step in a job?

Another timeout issue I seem to be having is when I include that job in a workflow. The workflow hits the job that should timeout, but it never times out. I have a timeout on the workflow as well and it doesn't time out either. 
Thanks.

**Comment by gschueler** [comment] 2015-01-22 18:23
I believe it should trigger retry on timeout, so I think this is a bug

**Comment by gschueler** [comment] 2015-01-22 18:45
I reproduced this as well.  I see an error log message that it can't start the job because it is already running. I think the bug is that the job is marked as "multiple executions: no", but it doesn't allow for retries when checking that.

so you might try a workaround by setting the job to "multiple executions: true"

**Comment by bdmorin** [comment] 2015-01-22 19:05
Thanks Greg, I did try the multiple executions setting as well.
Is there some other diagnostics I can provide?

**Comment by gschueler** [comment] 2015-01-22 19:29
any errors in your rundeck service log?

**Comment by bdmorin** [comment] 2015-01-22 19:34
I'll have to wait till afterhours to run the workflows so I don't interrupt folks. I'll update this evening.

**Comment by gschueler** [comment] 2015-01-27 22:13
@bdmorin any luck getting service log messages?

**Comment by gschueler** [comment] 2015-01-28 17:40
unable to reproduce in 2.4.0

**Comment by gschueler** [comment] 2015-01-29 20:05
I was able to get a similar behavior, I think it may be caused if the value of the Retry setting for the job accidentally has whitespace or otherwise can't be parsed as an integer.  It is allowed to use an option reference like `${option.retry}`, but after expanding the value, it is not validated until the retry is attempted.  This would cause the retry to fail with only an error mesage in the service log.

**Closed** 2015-01-30 00:57 UTC
Labels: bug, needs-review
