### ISSUE TITLE
2.6.6-1: The Execution Log could not be found.

### ISSUE THREAD

**Issue by dzarth** [rundeck/rundeck#1834] opened 2016-04-29 10:16 UTC
after the update to 2.6.6-1 jobs run using the cli (run command) sometimes fail and there is no execution log available. 

from the logs:
2016-04-29 11:42:06,805 [main] ERROR com.dtolabs.client.utils.WebserviceHttpClientChannel - Unable to parse result document: Error on line 14 of document  : An invalid XML character (Unicode: 0x7) was found in the value of attribute "loghtml" and element is "entry". Nested exception: An invalid XML character (Unicode: 0x7) was found in the value of attribute "loghtml" and element is "entry".
org.dom4j.DocumentException: Error on line 14 of document  : An invalid XML character (Unicode: 0x7) was found in the value of attribute "loghtml" and element is "entry". Nested exception: An invalid XML character (Unicode: 0x7) was found in the value of attribute "loghtml" and element is "entry".
<...>
Nested exception: 
org.xml.sax.SAXParseException; lineNumber: 14; columnNumber: 280; An invalid XML character (Unicode: 0x7) was found in the value of attribute "loghtml" and element is "entry".

using the webinterface to rerun the failed job it is working fine. We have 2 nodes behind a loadbalancer using a shared mysql. If you have any further questions, please let me know.

Many thanks in advance,
Dirk

**Comment by gschueler** [comment] 2016-05-02 17:51
can you send the ".rdlog" file corresponding to one of the executions that show that error?

**Comment by dzarth** [comment] 2016-05-06 07:15
I have to apologize. Thanks for pointing me to the rdlogs. I have now created a synchronization of logs between the nodes as described in the documentation and it is working fine. Again, I’m sorry. 

Many Thanks,
Dirk

**Comment by atlasloewenherz** [comment] 2016-05-18 11:40
@gschueler  i think now you can close this one, as of the comment above this not a bug.

**Closed** 2016-05-18 18:47 UTC
Labels: bug
